### ISSUE TITLE
No advantage, whereabouts can basically do it

### ISSUE THREAD

**Issue by BurlyLuo** [spidernet-io/spiderpool#1051]
**1 Code requirement**

necessary comment for your additional code , and comment for goDoc

function and variable name must not be at will

do not make huge function

**2 observe opensource license**

announce license at the beginning of file

**3 sign-off your commit**

your commit must be signed off

**4 Is your feature request related to a problem? Please describe.**

**5 Describe the solution you'd like**

**6 Describe alternatives you've considered**

**7 Additional context**

**Comment by iiiceoo** [comment]
@BurlyLuo I see that you described similar questions in #1052. If there are no other ideas that need to be discussed separately, please close this issue. We will reply you in another issue, thanks.

**Comment by weizhoublue** [comment]
before the project , we have looked into kinds of IPAM and CNI project, including whereabouts, 
We designed kinds of new features , such as static ip.  you could refer to the usage doc for details
