### ISSUE TITLE
docs:The usage document does not explain the usage of default-v4-subnet

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#1099]
https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/spider-subnet.md

After the spiderpool plugin is installed, default-subnet and default-pool will be generated by default, but they cannot allocate to applications. You need to expand the subnet or build another subnet

**Comment by yulng** [comment]
In the future, the UI will filter out the IP pool with no remaining IP addresses

**Comment by Icarus9913** [comment]
https://github.com/spidernet-io/spiderpool/pull/1205
