### ISSUE TITLE
potential panic for spiderpool controller 

### ISSUE THREAD

**Issue by Icarus9913** [spidernet-io/spiderpool#1104]
**Describe the bug**
Once we meet not exist case, we should return nil right now. Otherwise, we'll meet no pointer panic in the next processing steps

https://github.com/spidernet-io/spiderpool/blob/8f46b25e7801ae212948b1aeb27a38d1ceaff8c6/pkg/subnetmanager/subnet_controller.go#L600-L606

**Comment by ty-dc** [comment]
fix #1103
