### ISSUE TITLE
Night CI 2022-12-08: Failed, the automatic pool label deparse fails.

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1161]
action url: https://github.com/spidernet-io/spiderpool/actions/runs/3651786303

**Comment by ty-dc** [comment]
Upload the zip file generated from that test failure.
[dualstack-debuglog.txt (2).zip](https://github.com/spidernet-io/spiderpool/files/10190980/dualstack-debuglog.txt.2.zip)

**Comment by ty-dc** [comment]
The problem should be introduced by this [pr](#1135).

The empty pool was built only a few microseconds before it was deleted by itself.
![企业微信截图_16705548097887](https://user-images.githubusercontent.com/101157744/206614939-5595cb21-55d1-4b08-b306-615b2c62da73.png)

**Additional context**
If there is a "-" in the name of ns, the automatic pool label deparse fails.
