### ISSUE TITLE
Night CI 2022-12-10: Failed, the field status.allocatedIPCount of SpiderIPPool was incorrectly updated to -1

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1166]
action url: https://github.com/spidernet-io/spiderpool/actions/runs/3665784519

**Comment by ty-dc** [comment]
Upload the zip file generated from that test failure.
[dualstack-debuglog.txt (3).zip](https://github.com/spidernet-io/spiderpool/files/10203927/dualstack-debuglog.txt.3.zip)

**Comment by iiiceoo** [comment]
This is a bug caused by a typo, which will be fixed in #1169.
