### ISSUE TITLE
usage issue

### ISSUE THREAD

**Issue by gssjl2008** [spidernet-io/spiderpool#1221]
**usage issue**
1. doubts about how to use the software
使用 spiderpool 分配 ip，
示例：
10.10.10.1 - 10.10.10.10
10.10.10.20 - 10.10.10.30

我创建出  pool ，只使用一个 ip
假定 10.10.10.25 ， 如果要我查看可用的 ip ，

假如创建了 10+ 个随机的pool ，每个 pool 使用 1-2个 ip ，我要知道剩余可用的 ip，继续创建 pool ，好像挺困难，是否有好的办法来处理这个问题？

**Comment by iiiceoo** [comment]
从你的描述中，我理解为你希望能通过某些方式来知道一个 SpiderIPPool 或者一个子网下的多个 SpiderIPPool 的剩余 IP 地址（可用 IP 地址）。

先说结论，这个目前是没有实现的，出于设计的原因，我们仅保留与展示了 “已使用的 IP 地址” 而非 “可用的 IP 地址”。一个朴素的做法，在 IPPool CRD 的 status 定义中添加一个字段，用于表示当前可用的 IP 地址，这个做法看上去不错，但是短期来看我们不会这样做（因为没有它也不影响功能），不过未来可能会支持。

不支持这个能力的一个更大的原因就是，Spiderpool 未来的使用更多的会偏向于启用 [SpiderSubnet](https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/spider-subnet.md) 特性，通过纯子网的方式来管理 IP 地址。启用 SpiderSubnet 后，你只需要规划各个子网，而 SpiderIPPool 会被控制器自动的建立与管理，SpiderIPPool 对于用户将变得更加透明与不重要。

你提出来的问题，更多的会发生在禁用了 SpiderSubnet 特性时，人为的建立与维护 SpiderIPPool；这时候你可能需要事先做好网路规划，否则在 SpiderIPPool 的数量过大时，将会变得难以管理。

如果没有其他问题，请关闭这个 issue。

**Comment by gssjl2008** [comment]
👌，感谢解答
