### ISSUE TITLE
Night CI 2022-12-29: Failed to patch subnet resource

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1243]
action url: https://github.com/spidernet-io/spiderpool/actions/runs/3802892901

**Comment by weizhoublue** [comment]
any update ?

**Comment by ty-dc** [comment]
There may be a problem with the patch resource

**Comment by Icarus9913** [comment]
For the patch API
https://github.com/spidernet-io/spiderpool/blob/52abb89d6fbf8cb6d7f2076554b2d1ef9165091c/test/e2e/common/spidersubnet.go#L235-L242

It should add one PatchOption to make encounter updating conflict situation.
https://github.com/kubernetes-sigs/controller-runtime/blob/056869c967cd980d64dba1a16aa5b78e351ddaf1/pkg/client/options.go#L764-L767
@ty-dc
