### ISSUE TITLE
The spiderpool not work in customized namespace (not kube-system)

### ISSUE THREAD

**Issue by yankay** [spidernet-io/spiderpool#1253]
![image](https://user-images.githubusercontent.com/1469319/210537734-ec6da13c-2cfe-4f0c-8879-6fd7a09accaa.png)

**Comment by iiiceoo** [comment]
The components and CM of Spiderpool can work in any Namespace:

```bash
helm install spiderpool spiderpool/spiderpool --namespace {NAMESPACE_YOU_EXCEPT}
```

This should be a bug of Spidernet API, which has been solved at present.
