### ISSUE TITLE
[UT] failed to sets the reference of the controller Subnet

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#1274]
**Screenshots and log**
```
 [FAILED] Expected
      <bool>: false
  to be true
  In [It] at: /home/runner/work/spiderpool/spiderpool/pkg/ippoolmanager/ippool_webhook_test.go:215 @ 01/11/23 20:21:20.51
```
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/101157744/211968765-a78d3f17-0282-4e8a-bebd-aaf9b893202b.png">

**Additional context**
https://github.com/spidernet-io/spiderpool/actions/runs/3896380022/jobs/6652852628

**Comment by iiiceoo** [comment]
Under pkg ippoolmanager, I use `ginkgo run -p --until-it-fails` to continuously run the unit test in parallel, but no error is found. Yesterday, a [PR](https://github.com/spidernet-io/spiderpool/pull/1267) that bump github.com/onsi/ginkgo/v2 from 2.6.1 to 2.7.0 was merged, I guess the failure of this unit test may be related to the version change of ginkgo.

However, the ginkgo I used for local testing is also version 2.7.0. In my opinion, there should be no bug with the "error" test code, please close this issue until the error can be repeated again. Thank you!

**Comment by ty-dc** [comment]
https://github.com/spidernet-io/spiderpool/actions/runs/3920124700

The problem occurs again
