### ISSUE TITLE
Night CI 2023-02-13: Check Pod event failed

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1329]
action url: https://github.com/spidernet-io/spiderpool/actions/runs/4167463555

**Comment by ty-dc** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/101157744/218622777-03f95baa-f0e2-4d70-928d-f4c31b537628.png">

**Comment by ty-dc** [comment]
#1301
