### ISSUE TITLE
Promote Link at other repos

### ISSUE THREAD

**Issue by yankay** [spidernet-io/spiderpool#1331]
Promote Link at other repos, like

- https://github.com/containernetworking/cni
- https://github.com/kubernetes/website/blob/main/content/zh-cn/docs/concepts/cluster-administration/addons.md

**Comment by weizhoublue** [comment]
great , after 0.4.0 released recently , lots of these work will proceed

**Comment by Icarus9913** [comment]
https://github.com/kubernetes/website/pull/44097/files
