### ISSUE TITLE
License Scan failures

### ISSUE THREAD

**Issue by pacoxu** [spidernet-io/spiderpool#1352]
https://app.fossa.com/projects/git%2Bgithub.com%2Fpacoxu%2Fspiderpool/refs/branch/main/fdf1eb5a53d1c6b02f2caeae5011647f13498338/issues/licensing/3080512

1. Flagged: GPL-3.0-only in moby（File: contrib/init/openrc/docker.initd）
2.   Flagged: LGPL-3.0-or-later in moby（File: vendor/github.com/containerd/cgroups/v2/devicefilter.go）

https://github.com/spidernet-io/spiderpool/blob/fdf1eb5a53d1c6b02f2caeae5011647f13498338/pkg/workloadendpointmanager/utils_test.go#L9
https://github.com/spidernet-io/spiderpool/blob/fdf1eb5a53d1c6b02f2caeae5011647f13498338/pkg/workloadendpointmanager/workloadendpoint_manager_test.go#L13

- **我目前感觉这个扫描出来的这个 license 问题不大。**

目前使用到 moby 的两个都是测试。
- 方便的话，可以把这个依赖 换掉，或者把相关代码放到一个地方单独维护，会麻烦一点。

**Comment by iiiceoo** [comment]
目前导入 moby 只是为了在测试中更真实的生成 ContainerID 这个字段，后续自己维护一个类似的工具函数来做这个事就行了，不需要额外的导入 moby。等之后相关 PR 提上来了会关联这个 issue。
