### ISSUE TITLE
创建subnet后未生成ippool

### ISSUE THREAD

**Issue by pengbinbin1** [spidernet-io/spiderpool#1382]
按照文档说明，创建了subnet资源后会生成对应的ippool，但是实际操作中并未生成，使用版本为0.3.6   报错日志如下图所示
<img width="920" alt="jietu" src="https://user-images.githubusercontent.com/28950491/221558413-ceff1e0f-789e-4a80-a7b6-99a08d01d1e0.png">

**Comment by Icarus9913** [comment]
能否贴一下spiderpool-controller的日志呢？注意spiderpool-cotroller是有主备机制的，leader的那个才会工作，麻烦贴一下。

另外需要注意的一点是，若spiderpool安装后，未在helm中选定启用subnet功能，后续想使用subnet功能，是要在configmap spiderpool-conf中修改的，且重启spiderpool-agent和spiderpool-controller组件（因为不支持热加载）

**Comment by pengbinbin1** [comment]
controller的日志如下如所示：
<img width="820" alt="jietu" src="https://user-images.githubusercontent.com/28950491/222024405-fc94a1a0-330c-4d44-8d0f-554c585a92ab.png">

**Comment by pengbinbin1** [comment]
> 能否贴一下spiderpool-controller的日志呢？注意spiderpool-cotroller是有主备机制的，leader的那个才会工作，麻烦贴一下。
> 
> 另外需要注意的一点是，若spiderpool安装后，未在helm中选定启用subnet功能，后续想使用subnet功能，是要在configmap spiderpool-conf中修改的，且重启spiderpool-agent和spiderpool-controller组件（因为不支持热加载）

修改configmap后重启了agent和controller  并且controller是单副本部署
![微信图片_20230301094930](https://user-images.githubusercontent.com/28950491/222024667-2b939f9e-c352-4ad9-bd29-666ffb35ceda.jpg)

**Comment by pengbinbin1** [comment]
创建subnet后查看ippool 依然没有自动生成的ippool
![微信图片_20230301094917](https://user-images.githubusercontent.com/28950491/222024790-1e1e6f38-b865-42be-87a8-2188a39e1835.jpg)

**Comment by Icarus9913** [comment]
从spiderpool-controller的日志来看，似乎你的这个k8s集群不支持cronjob？是不是版本过低了？

麻烦再在spiderpool-controller中查看一下是否有"application controller workers started"这行日志，或者是否有“failed to run application controller, error”这行报错。 spiderpool-controller是有readiness机制的，感觉目前提供的这个日志还不是很全，后续应该还有一些日志。

另外建议修改一下spiderpool-controller的日志级别，修改其deployment中的env中日志级别"SPIDERPOOL_LOG_LEVEL"改成debug。 重启后麻烦重新看一下controller的日志信息，谢谢。

**Comment by pengbinbin1** [comment]
查看了整个日志的全量里面都没"application controller workers started"或者“failed to run application controller, error”   只有“try to register applications controller” 和 “create application informer”

**Comment by pengbinbin1** [comment]
k8s版本是1.20的，如果不支持cronjob创建subnet就不会生成ippool了？ 他们之间有直接关系吗？

**Comment by pengbinbin1** [comment]
[controller.txt](https://github.com/spidernet-io/spiderpool/files/10858051/controller.txt)

**Comment by Icarus9913** [comment]
spiderpool-controller看ENV里有没有SPIDERPOOL_SUBNET_INFORMER_WORKERS，这个调整成为5试试看

**Comment by pengbinbin1** [comment]
> spiderpool-controller看ENV里有没有SPIDERPOOL_SUBNET_INFORMER_WORKERS，这个调整成为5试试看

设置为5还是跟之前一样呢

**Comment by Icarus9913** [comment]
> > spiderpool-controller看ENV里有没有SPIDERPOOL_SUBNET_INFORMER_WORKERS，这个调整成为5试试看
> 
> 设置为5还是跟之前一样呢

这就有点奇怪了。这样，麻烦先把你的那个业务deployment删掉，然后重新复现一下(把spiderpool-agent和controller组件全部重启一下，另外把ENV中的log级别改成debug)。

然后提供，
1. 业务deployment的yaml信息，看一下annotation是否正确
2.业务pod启动的那个节点的spiderpool-agent的日志
3. spiderpool-controller的日志，以及spiderpool-controller的ENV配置

**Comment by pengbinbin1** [comment]
![deploy](https://user-images.githubusercontent.com/28950491/222308595-5bf681ce-71f6-4313-a278-dcc5a30deeac.jpg)
![ENV](https://user-images.githubusercontent.com/28950491/222308636-6fb07f1b-6ba9-4bfd-b897-42b32f8a9a1f.jpg)

**Comment by pengbinbin1** [comment]
[controller.log](https://github.com/spidernet-io/spiderpool/files/10866806/controller.log)
[agent.log](https://github.com/spidernet-io/spiderpool/files/10866807/agent.log)

**Comment by Icarus9913** [comment]
ok, 看了一下代码。能确定是因为cronjob没有ready导致的了。
```go 
	logger.Debug("Waiting for application informers caches to sync")
	ok := cache.WaitForCacheSync(stopCh,
		c.deploymentInformer.HasSynced,
		c.replicaSetInformer.HasSynced,
		c.daemonSetInformer.HasSynced,
		c.statefulSetInformer.HasSynced,
		c.jobInformer.HasSynced,
		c.cronJobInformer.HasSynced,
	)
	if !ok {
		return fmt.Errorf("failed to wait for caches to sync")
	}
```
其中这个`WaitForCacheSync`函数是个轮训的动作，他没有ready的话就不会往下走了。 建议把你的Kubernetes集群看一下，把cronjob资源补上

**Comment by pengbinbin1** [comment]
> ok, 看了一下代码。能确定是因为cronjob没有ready导致的了。
> 
> ```go
> 	logger.Debug("Waiting for application informers caches to sync")
> 	ok := cache.WaitForCacheSync(stopCh,
> 		c.deploymentInformer.HasSynced,
> 		c.replicaSetInformer.HasSynced,
> 		c.daemonSetInformer.HasSynced,
> 		c.statefulSetInformer.HasSynced,
> 		c.jobInformer.HasSynced,
> 		c.cronJobInformer.HasSynced,
> 	)
> 	if !ok {
> 		return fmt.Errorf("failed to wait for caches to sync")
> 	}
> ```
> 
> 其中这个`WaitForCacheSync`函数是个轮训的动作，他没有ready的话就不会往下走了。 建议把你的Kubernetes集群看一下，把cronjob资源补上

好的 ，谢谢。个人觉得这块逻辑是否可以优化一下，不要因为某一个资源不支持而影响其他资源的正常运行

**Comment by Icarus9913** [comment]
后续会考虑一下
