### ISSUE TITLE
failed to create a spiderpool in kind cluster

### ISSUE THREAD

**Issue by Fish-pro** [spidernet-io/spiderpool#1391]
**usage issue**

1.Use kind to start a cluster with the following configuration
```
kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  podSubnet: "10.244.0.0/16"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
```

2.Use the following command to install spiderpool
```bash
$ export IPV4_SUBNET_YOU_EXPECT="10.244.0.0/16"
$ export IPV4_IPRANGES_YOU_EXPECT="10.244.0.40-10.244.0.200"
$ helm install spiderpool spiderpool/spiderpool --namespace kube-system \
  --set spiderpoolController.tls.method=auto \
  --set feature.enableIPv4=true --set feature.enableIPv6=false \
  --set clusterDefaultPool.installIPv4IPPool=true  \
  --set clusterDefaultPool.ipv4Subnet=${IPV4_SUBNET_YOU_EXPECT} \
  --set clusterDefaultPool.ipv4IPRanges={${IPV4_IPRANGES_YOU_EXPECT}}
```

3.Modify CNI configurations
```bash
{
	"cniVersion": "0.3.1",
	"name": "kindnet",
	"plugins": [
	{
		"type": "ptp",
		"ipMasq": false,
                "ipam":{
                   "type":"spiderpool"
                },
		"mtu": 1500

	},
	{
		"type": "portmap",
		"capabilities": {
			"portMappings": true
		}
	}
	]
}
```

4.failed to create a spiderpool
```bash
➜  Downloads cat spiderpool.yaml
apiVersion: spiderpool.spidernet.io/v1
kind: SpiderIPPool
metadata:
  name: custom-ipv4-ippool
spec:
  ipVersion: 4
  subnet: "10.244.0.0/16"
  ips:
  - "10.244.0.41"
➜  Downloads kubectl create -f spiderpool.yaml
The SpiderIPPool "custom-ipv4-ippool" is invalid: spec.ips: Forbidden: overlap with IPPool default-v4-ippool in IP ranges [10.244.0.41], total IP addresses of an IPPool are jointly determined by 'spec.ips' and 'spec.excludeIPs'
```

### Version
```
➜  Downloads kubectl -n kube-system get po spiderpool-controller-cddcbb78f-d8slg -o yaml | grep image:
    image: ghcr.io/spidernet-io/spiderpool/spiderpool-controller:v0.3.7
    image: ghcr.io/spidernet-io/spiderpool/spiderpool-controller:v0.3.7
```

**Comment by Fish-pro** [comment]
I understand. There is no overlapping IP. Why did you report an error
```bash
	Describe("Test IPsIntersectionSet", func() {
		It("finds the intersection set of two groups of IPv4 addresses", func() {
			ips := spiderpoolip.IPsIntersectionSet(
				[]net.IP{
					net.IPv4(172, 18, 40, 1),
					net.IPv4(172, 18, 40, 2),
				},
				[]net.IP{
					net.IPv4(172, 18, 40, 2),
					net.IPv4(172, 18, 40, 3),
				},
				true,
			)
			Expect(ips).To(Equal([]net.IP{net.IPv4(172, 18, 40, 2)}))
		})
```

**Comment by Fish-pro** [comment]
The document I use is
https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/basic.md

**Comment by ty-dc** [comment]
In step 2, you installed the default pool
```
$ export IPV4_SUBNET_YOU_EXPECT="10.244.0.0/16"
$ export IPV4_IPRANGES_YOU_EXPECT="10.244.0.40-10.244.0.200"
$ helm install spiderpool spiderpool/spiderpool --namespace kube-system \
  --set spiderpoolController.tls.method=auto \
  --set feature.enableIPv4=true --set feature.enableIPv6=false \
  --set clusterDefaultPool.installIPv4IPPool=true  \
  --set clusterDefaultPool.ipv4Subnet=${IPV4_SUBNET_YOU_EXPECT} \
  --set clusterDefaultPool.ipv4IPRanges={${IPV4_IPRANGES_YOU_EXPECT}}
```
Please confirm whether there is overlap between the default-v4-ippool you installed and custom-v4-ippool.

** View the created IPPool **
-  kubectl get sp

**Comment by Fish-pro** [comment]
@ty-dc 
Thanks for the guidance, the problem has been solved。
However, if you follow the example, you will get an error. Can we change the ip range of the example

**Comment by ty-dc** [comment]
https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/basic.md

The v4-default-pool range given in the sample document is:
```
IPV4_SUBNET_YOU_EXPECT="172.18.40.0/24"
IPV4_IPRANGES_YOU_EXPECT="172.18.40.40-172.18.40.200"
```
Create a custom IPPool. The YAML file looks like:
```
apiVersion: spiderpool.spidernet.io/v1
kind: SpiderIPPool
metadata:
  name: custom-ipv4-ippool
spec:
  ipVersion: 4
  subnet: 172.18.41.0/24
  ips:
  - 172.18.41.40-172.18.41.50
```
Therefore, if you operate according to the document, there should be no unexpected error.
They are not in the same subnet, and the IP range does not overlap

**Comment by Fish-pro** [comment]
> https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/basic.md
> 
> The v4-default-pool range given in the sample document is:
> 
> ```
> IPV4_SUBNET_YOU_EXPECT="172.18.40.0/24"
> IPV4_IPRANGES_YOU_EXPECT="172.18.40.40-172.18.40.200"
> ```
> 
> Create a custom IPPool. The YAML file looks like:
> 
> ```
> apiVersion: spiderpool.spidernet.io/v1
> kind: SpiderIPPool
> metadata:
>   name: custom-ipv4-ippool
> spec:
>   ipVersion: 4
>   subnet: 172.18.41.0/24
>   ips:
>   - 172.18.41.40-172.18.41.50
> ```
> 
> Therefore, if you operate according to the document, there should be no unexpected error. They are not in the same subnet, and the IP range does not overlap

@ty-dc Thanks, I got it
