### ISSUE TITLE
Chart usage readme file need to specific

### ISSUE THREAD

**Issue by wilsonwu** [spidernet-io/spiderpool#146]
**Documentation issue**
1. [miss documentation](https://github.com/spidernet-io/spiderpool/tree/main/charts/spiderpool), suggest some values meaning and usage command shown in this page.
2. also suggest to add the help doc into doc site.

**Comment by weizhoublue** [comment]
1 need add some comments directly on the value.yaml and README.md  
@iiiceoo could handle it in August

2 it is under way

**Comment by weizhoublue** [comment]
done
