### ISSUE TITLE
Night CI 2023-03-21: Failed to release IP 

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1515]
action url: https://github.com/spidernet-io/spiderpool/actions/runs/4483438335

**Comment by Icarus9913** [comment]
According to the spiderpool-controller logs, the IP GC pod informer doesn't record the pod events to the PodDB because of all of the spiderpool-controllers did not acquire the leader. 

So, we need optimize the IP GC pod informer startup operation

**Comment by Icarus9913** [comment]
And the e2e test do not set to much waiting time to wait for IP GC `scan all`.
