### ISSUE TITLE
wrong helm installation property 

### ISSUE THREAD

**Issue by Icarus9913** [spidernet-io/spiderpool#1522]
**Describe the version**
version about:
1. spiderpool `v0.4.0-rc4`

**Describe the bug**
The spiderpool-controller IP-GC env already changed.
For example: `SPIDERPOOL_GC_TERMINATING_POD_IP_DELAY ` already switched to `SPIDERPOOL_GC_ADDITIONAL_GRACE_DELAY `

**Comment by ty-dc** [comment]
fix #1521
