### ISSUE TITLE
ginkgo:  [FAILED] Test Report unavailable because a Ginkgo parallel process disappeared

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1537]
action url: https://github.com/spidernet-io/spiderpool/actions/runs/4526421734

**Comment by iiiceoo** [comment]
This occurs if a parallel process exits before it reports its results to the Ginkgo CLI. The issue cannot be replicated locally, and it should be harmless. 

During parallel testing, if panic occurs in certain specs, this error may be reported. However, during local testing, no panic occurs. Therefore, I believe that our test case should be correct, which should be considered as a minor issue with ginkgo. Don't close this issue, maybe it will happen again.

**Comment by iiiceoo** [comment]
BTW, we can use `--output-interceptor-mode=none` to disable ginkgo from capturing stdout/stderr output to avoid test suite failures due to missing reports from related processes, but we should not do this because we need ginkgo's reports to debug.

**Comment by ty-dc** [comment]
#2009
