### ISSUE TITLE
[test]After deleting unused IP in the automatic pool, the number of subnets does not match

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#1609]
[test]After deleting unused IP in the automatic pool, the number of subnets does not match
[env]
http://10.5.14.51:32292/spidernet/clusters/network-offline/subnets/detail/subnet01
[version]spiderpool:0.4.0;spidernet:0.5.0
[step]
1 Remove unused IPs from the automatic pool
2 Not returning to the subnet, resulting in quantity deviation
subnet：98/100
ippool01：2/95
autopool：2/4

![企业微信截图_1f3a59b7-5cf8-4fd5-9f52-1b432abda613](https://user-images.githubusercontent.com/31728060/229674224-6648e460-2700-448c-b2c7-98112b485ea5.png)

![企业微信截图_b40ebcb0-1277-4313-9750-6c73712792b0](https://user-images.githubusercontent.com/31728060/229674243-d06119b2-7679-41e8-bb9b-75de86473bce.png)

![企业微信截图_47c431ca-960f-4790-bfd0-62371553ce38](https://user-images.githubusercontent.com/31728060/229674263-0288b917-500b-4f2b-8470-acccd459a835.png)

**Comment by ty-dc** [comment]
#1611
