### ISSUE TITLE
popularization 

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1651]
## post

     how the auto ippool work
     spidepool with sriov
     spidepool with weave
     application across network zone
     performance
     gc issue
     route design when multiple interface

## pr

    antrea
    kubespray
    kubesphere
    kube-ovn

**Comment by ty-dc** [comment]
The corresponding documentation has been completed, please pay attention to the website.

https://spidernet-io.github.io/spiderpool/v0.8/
