### ISSUE TITLE
【test】the automatic pool and its IP have not been released (gc)

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#1659]
【test】the automatic pool and its IP have not been released (gc)

![企业微信截图_628a830e-cd1f-4f57-ae4a-68ba8a81c6f5](https://user-images.githubusercontent.com/31728060/231715856-80eacd5e-8bb0-467d-bbc9-f5fa325fd7dc.png)

【version】spiderpool:0.4.0;spidernet:0.5.0

Step:
1 Create a statefulset with the same name in different namespaces(default and kube-system)
2. Rename a node spiderpool bin file(/opt/cni/bin/spiderpool)
3. Delete the statefulset of the kube-system namespace for this node
4 statefulset has been in the Terminating state, and the automatic pool and its IP have not been released

![image](https://user-images.githubusercontent.com/31728060/231719746-8c6fc60c-f402-46e5-b6b9-59ff769e4c22.png)

**Comment by Icarus9913** [comment]
It looks like that the IP GC ignore to release StatefulSet terminating pod whether the pod is valid or not
