### ISSUE TITLE
IP GC not in time

### ISSUE THREAD

**Issue by Icarus9913** [spidernet-io/spiderpool#1662]
**Describe the version**
version about:
1. spiderpool `v0.4.0`

**Describe the bug**
Every time spiderpool-controller pod starts, no matter it's a leader or backup it all will run scan all at first. And the IP GC pod-informer mechanism rely on leader election, this will cost some time. But what if I delete some pods between the two operations, the pod informer doesn't start and even it starts it can't receive pod delete events.

This may cause the IP GC not in time.

**Comment by ty-dc** [comment]
#1661
