### ISSUE TITLE
The document page has a dead link: https://spidernet-io.github.io/spiderpool/usage/multiple-subnet.md

### ISSUE THREAD

**Issue by luxinglei** [spidernet-io/spiderpool#1680]
**open page https://spidernet-io.github.io/spiderpool/；will see the following：**

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/53964997/233330458-48e390c2-4d7c-4f27-9672-bef12edf29bd.png">

**Clicking on it will redirect you to an empty page.**
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/53964997/233331472-b1532c6f-2b9c-42b5-aa6c-fb32c5c34f15.png">

**[This link](https://spidernet-io.github.io/spiderpool/usage/multiple-subnet.md) is a meaningless dead link**

**Comment by ty-dc** [comment]
THX！It will be fixed soon

**Comment by ty-dc** [comment]
Fixed, not showing up as NONE on the page
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/101157744/236363823-6d417710-bfcf-4de9-be15-48f4c49e983b.png">
