### ISSUE TITLE
auto-created pool reconcile algorithm bug

### ISSUE THREAD

**Issue by Icarus9913** [spidernet-io/spiderpool#1692]
**Describe the version**
version about:
1. spiderpool `v0.4.0`

**Describe the bug**

https://github.com/spidernet-io/spiderpool/blob/0102dbf2afd24467bf8bbd2316c830ab92bdf55e/pkg/subnetmanager/subnet_manager.go#L231-L234

In the auto-created IPPool shrink operation, we'll update the SpiderSubnet.Status.ControlledIPPools first and update the auto-created IPPool.Spec.IPs later. But if the first update operation succeeded and the latter operation failed, the two IPs will be difference. As the length of the two IPs are equal, so we could just use `difference sets` to check it.

I used the wrong check function `IPsIntersectionSet ` to check it.

**Comment by ty-dc** [comment]
#1693
