### ISSUE TITLE
spiderpool can not work well with calico

### ISSUE THREAD

**Issue by pengbinbin1** [spidernet-io/spiderpool#1723]
I want to use spiderpool as the IPAM on my cluster, cluster's CNI is Calico . I have refered the [document ](https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/get-started-calico.md)on github.But when i changed the Calico IPAM type to "spiderpool",it will convert backed to "calico-ipam",what's wrong? My spiderpool version:v0.4.0    k8s version: v1.26   calico version: v3.24.5

**Comment by iiiceoo** [comment]
How to understand the meaning of "convert backed to `calico-ipam`"? Please provide a more accurate and detailed description.

**Comment by Icarus9913** [comment]
> convert backed to "calico-ipam"
You mean the `/etc/cni/net.d/* ` cni configuration turns back to `ipam: calico-ipam` ?

Do you use multus?  Did you changed the all nodes cni configurations?

**Comment by pengbinbin1** [comment]
> How to understand the meaning of "convert backed to `calico-ipam`"? Please provide a more accurate and detailed description.
参考文档，部署完成环境后，修改每个节点的10-calico.conflist,将ipam的type字段改为“spiderpool”，重启每个节点的calico-node，再查看刚修改过的配置文件，ipam的type又变回了“calico-ipam”

**Comment by pengbinbin1** [comment]
> > convert backed to "calico-ipam"
> > You mean the `/etc/cni/net.d/* ` cni configuration turns back to `ipam: calico-ipam` ?
> 
> Do you use multus? Did you changed the all nodes cni configurations?

没有使用multus

**Comment by weizhoublue** [comment]
I  think it should modify the calico CNI config by two ways:

(1) modify the configmap

<img width="472" alt="企业微信截图_17eab5a8-7e37-4fea-b40a-7e849787e1d2" src="https://user-images.githubusercontent.com/45163302/234763755-d807dc2f-af38-45e3-8756-0e20a497b142.png">

(2) use multus CR to define calico configuration

**Comment by weizhoublue** [comment]
it could change the configuring way in the usage document

**Comment by cyclinder** [comment]
Thanks for the report @pengbinbin1 

Yes, document's method is not persistent, when calico-node is restarted, calico's cni configuration goes back to the original configuration. At this point, We will improve the documentation.

a workaround is: update calico's configmap  `calico-config` and change the value of the ipam field to `spiderpool`.
