### ISSUE TITLE
some doc is out of date

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1756]
(1) miss some annotation in markdown

https://github.com/spidernet-io/spiderpool/blob/main/docs/concepts/annotation.md

miss following:

ipam.spidernet.io/ippool-ip-number

ipam.spidernet.io/ippool-reclaim

(2) miss default values

https://github.com/spidernet-io/spiderpool/blob/main/docs/concepts/config.md

**Comment by Icarus9913** [comment]
processing
