### ISSUE TITLE
underlay standalone

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1902]
for clusterip , need to do some configuration:
(1) kube proxy , masquerade-all
(2) cilium  , kubeproxy-replacement

**Comment by weizhoublue** [comment]
@cyclinder

**Comment by cyclinder** [comment]
It will be finished in https://github.com/spidernet-io/spiderpool/pull/2441

**Comment by ty-dc** [comment]
#2441 has been completed and we will close this issue.
