### ISSUE TITLE
自定义ippool没有默认继承subnet的路由配置

### ISSUE THREAD

**Issue by leolingg** [spidernet-io/spiderpool#1958]
**Describe the version**
version about:
1. spiderpool：v0.5.0
2. kubernetes：v1.25.4
3. what CNI and itsversion：calico v3.25.1, multus-cni v3.9

**Describe the bug**
自定义ippool没有默认继承subnet的路由配置

**How To Reproduce**
创建一个subnet并配置自定义路由，在基于此subnet创建一个ippool。

**Expected behavior**
自定义ippool可以默认继承subnet的路由配置。

**Screenshots and log**
![image](https://github.com/spidernet-io/spiderpool/assets/26449069/b7955438-653d-4251-93c3-40834d2caef4)
![image](https://github.com/spidernet-io/spiderpool/assets/26449069/afa667ae-8587-4a61-a49b-d3f4cdeee8a3)

**Additional context**

**Comment by ty-dc** [comment]
自定义池不会继承子网中的路由信息，自动池是会继承的。
