### ISSUE TITLE
localdns issue

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2031]
localDNs hijack dns request to 169.254.25.10 , so , when deployed with localDNs, the document could mention set  cni.externalCIDr  in the coordinator

**Comment by cyclinder** [comment]
Fixed by https://github.com/spidernet-io/spiderpool/pull/2012

We can configure the address of `localDNS` in helm values, example:

```
helm install spiderpool -n kube-system . --set coordinator.hijackCIDR={169.254.25.10}
```
