### ISSUE TITLE
reduplicated ipam allocation routes

### ISSUE THREAD

**Issue by Icarus9913** [spidernet-io/spiderpool#2033]
**Describe the version**
version about:
1. spiderpool v0.6.0

**Describe the bug**
The spiderpool IPAM allocation owns the routes, and they come from "annotation specification", "IPPool spec routes", "IPPool gateway default routes".
If there are some reduplicated routes, the codes don't filter them. We need fix this bug.

**Comment by ty-dc** [comment]
@Icarus9913 ？

**Comment by Icarus9913** [comment]
follow the current route rules
