### ISSUE TITLE
failed to access nodePort for underlay CNI

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2039]
for the service with externalTrafficPolicy=local,  fails to access the nodePort, because the node forward the packet to pod by veth and does not SNAT, then the pod reply throuth eth0, so the reply packet fails to do unDnat  
this does matter keeping the source IP for nodePort

**Comment by weizhoublue** [comment]
use following way to mark the packet and use `ip rule` to forward the reply packet throuth veth0
```
iptables -t mangle -A PREROUTING -i ipip0  -m conntrack --ctstate NEW -j MARK --set-mark 1
iptables -t mangle -A PREROUTING -m mark --mark 0x1 -j CONNMARK --save-mark
iptables -t mangle -A OUTPUT -j CONNMARK --restore-mark
```

**Comment by cyclinder** [comment]
fixed in https://github.com/spidernet-io/spiderpool/pull/2078
