### ISSUE TITLE
multiple queue for pod NIC

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2062]
set the numtxqueues and numrxqueues bigger than one, in the netowrk ns of pod

refer to https://github.com/projectcalico/cni-plugin/pull/1116

```
~# ip -d l show eth0
2: eth0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:20:18:14 brd ff:ff:ff:ff:ff:ff promiscuity 1 minmtu 68 maxmtu 65535 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 parentbus virtio parentdev virtio0
    altname enp0s3

```

**Comment by cyclinder** [comment]
Can you explain more details about it?

**Comment by cyclinder** [comment]
1. multiple queue for pod NIC for macvlan and ipvlan is don't make sense, see https://github.com/containernetworking/plugins/pull/986
2. multiple queue for sriov is set by nic driver, see https://github.com/k8snetworkplumbingwg/sriov-cni/issues/286
3. txqueuelen is suppored by https://github.com/spidernet-io/spiderpool/pull/2650
