### ISSUE TITLE
bug: the kubeconfig of multus used by spiderpoll has a too short expiration period

### ISSUE THREAD

**Issue by hansedong** [spidernet-io/spiderpool#2182]
**Describe the version**

version about:
1. spiderpool 0.6.0
2. kubernetes 1.27.4
3. what CNI and itsversion: cni-plugins 1.3.0

**Describe the bug**

I tried using spiderpool as the CNI for macvlan, but after deploying the pod instance, I encountered the following error.

```shell
0s          Warning   FailedCreatePodSandBox   pod/test-app-55689bfd4c-wh9r6    (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f9c0d3e6924472efda353e2068559634eb916661cb9e9ec4b0a31653572508d8": plugin type="multus" name="multus-cni-network" failed (add): Multus: [default/test-app-55689bfd4c-wh9r6/88d03583-3908-4084-b919-9b8fb370165a]: error getting pod: Unauthorized
```

I checked the kubeconfig of multus and found that it has indeed expired.

```shell
[root@xxx multus.d]# cat multus.kubeconfig
# Kubeconfig file for Multus CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://[10.249.0.1]:443
    certificate-authority-data: xxxxxxxxxxxxxx***==
users:
- name: multus
  user:
    token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Imo5dC1wZTVWUHNaN1pTRmpFWHJfNHh3Nk53WHdkNE5FVWNBU0FrMGswYzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjkxNzMzNzk4LCJpYXQiOjE2OTE3MzAxOTEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInBvZCI6eyJuYW1lIjoic3BpZGVycG9vbC1tdWx0dXMteGdmOXgiLCJ1aWQiOiJmNDk2OGM0ZC0xZDU2LTQ0NDMtOWMwNS1kNzhjYTRiMTc3MDQifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6InNwaWRlcnBvb2wtbXVsdHVzIiwidWlkIjoiZDRhNDEyNDItOTJmMC00MmY1LWJiZTctZjFjZmUyYjhjNDcxIn19LCJuYmYiOjE2OTE3MzAxOTEsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpzcGlkZXJwb29sLW11bHR1cyJ9.V8F6yFspCWqqbZC94weYNM6UFc4okDZQtS7grV7dyzVOLFJO-EOMSBmvW3uApP8s9UDS101TQAAOX2bQCKrvLN0m132M0V7dFE1QyuDspv0VfuhPMBSBl2u53BAJolFzrh_eM0Vp8VyV_4ELYqQmg5yRyVXKZS0orq4RFQl5WBUlReVWzkwSJhFrapK-u4ys_-n1-wbAnEIAvNyvcfHNuKLcVin75yTUJShxOShwBAPsJeYP75BrXGpeQkhUYw0fzgIldnOm7_S3qEOmpJYKoF-ykb0r6a5N1JGQcFOR6Z3SysZbWKZiqYLLRJAxHgNmaI7_MWDfgGy8wYnvLBV7jQ"
contexts:
- name: multus-context
  context:
    cluster: local
    user: multus
current-context: multus-context
```
the JWT payload is:

```shell
{
  "aud": [
    "https://kubernetes.default.svc.cluster.local"
  ],
  "exp": 1691733798,
  "iat": 1691730191,
  "iss": "https://kubernetes.default.svc.cluster.local",
  "kubernetes.io": {
    "namespace": "kube-system",
    "pod": {
      "name": "spiderpool-multus-xgf9x",
      "uid": "f4968c4d-1d56-4443-9c05-d78ca4b17704"
    },
    "serviceaccount": {
      "name": "spiderpool-multus",
      "uid": "d4a41242-92f0-42f5-bbe7-f1cfe2b8c471"
    }
  },
  "nbf": 1691730191,
  "sub": "system:serviceaccount:kube-system:spiderpool-multus"
}
```

> This kubeconfig token has a validity period of only 1 hour.

**How To Reproduce**

**Expected behavior**

**Screenshots and log**

**Additional context**

**Comment by Icarus9913** [comment]
Reference: 
https://github.com/k8snetworkplumbingwg/multus-cni/issues/852
https://bugzilla.redhat.com/show_bug.cgi?id=1972490
https://bugzilla.redhat.com/show_bug.cgi?id=1972167

What about restarting all you multus DaemonSet pods?

**Comment by hansedong** [comment]
> https://github.com/k8snetworkplumbingwg/multus-cni/issues/852

I have previously read this issue. Although the issue is already closed, in reality, the official team has not resolved this problem. I am quite surprised that they closed the issue without addressing it properly. This kind of problem should not exist in theory.

> https://bugzilla.redhat.com/show_bug.cgi?id=1972490
> https://bugzilla.redhat.com/show_bug.cgi?id=1972167

These two posts seem to not mention a solution to this issue, and the events in the posts happened in 2021, which was a long time ago.

> What about restarting all you multus DaemonSet pods?

I don't think restarting the multus DaemonSet Pod is a fundamental solution to the problem.

Spiderpool is a fantastic plugin that can perfectly solve the pain points in our underplay scenario in many aspects. However, Spiderpool relies on Multus. From my understanding, the issue with Multus is due to the use of TokenRequest to generate tokens in higher versions of K8s. The validity period of these tokens is requested at the time when TokenRequest is initiated. In theory, tokens should rotate and client-go has already adapted to scenarios where token rotation occurs. I always feel that this issue should not exist.

**Comment by weizhoublue** [comment]
@cyclinder  I think this is related to reinstallation of multus ?
I remember you encountered because the config in /etc/cni/net.d/multus*** is garbage left by previous  installation of multus, just delete them and restart the multus, and everything work well

**Comment by cyclinder** [comment]
> @cyclinder I think this is related to reinstallation of multus ? 

I'm not sure, We need to take a further investigation.

> I have previously read this issue. Although the issue is already closed, in reality, the official team has not resolved this problem. I am quite surprised that they closed the issue without addressing it properly. 

Yeah, I've come across it before 😭

@hansedong Could you tell me how you install Spiderpool?  Also, Coul you show the manifests of multus daemonSet by using the following command?

```
kubectl get ds -n kube-sytem  multus -o yaml
```

**Comment by hansedong** [comment]
> @hansedong Could you tell me how you install Spiderpool? Also, Coul you show the manifests of multus daemonSet by using the following command? Which k8s version do you use? We tried to reproduce this problem on the local machine.

@cyclinder 

1. I installed spiderpool using helm according to the official documentation.
2. Unfortunately, I have already deleted spiderpool now. 😓
3. I suddenly remembered that when I first installed spiderpool using helm, I interrupted the operation（because the image pulling was slow, I realized that I should switch to a mirror in China. Therefore, I interrupted this operation.） and repeated the process of installing spiderpool with helm.

My kubernetes cluster version is 1.27.4

**Comment by cyclinder** [comment]
ah, now I believe it may be an issue caused by the Multus reinstallation.  Have you checked if the multus pod is running while the pod failed to start?

When you first install it, multus generates kubeconfig correctly, which is stored in the `/etc/cni/net.d/multus/`. and you install it in the second time, maybe the multus pod didn't start properly and didn't generate a new kubeconfig, resulting in the old kubeconfig being used while the pod in creating.

So I believe restarting the multus pods can solve the problem. I have filed an issue for this, and I wanted Multus to manually clean up its CNI configuration files at each uninstallation to avoid such issues. they did not discuss it further and closed the issue. refer to https://github.com/k8snetworkplumbingwg/multus-cni/issues/1105.

**Comment by hansedong** [comment]
@cyclinder I will try to redeploy and test it in the K8s testing cluster later, simulating the scenario of reinstalling multus.

**Comment by Icarus9913** [comment]
Spiderpool v0.6.0 helm charts looks like install the multus with v3.9.3, and I checked the v3.9.3 source codes found multus reads '/var/run/secrets/kubernetes.io/serviceaccount/token' and write it to "/etc/cni/net.d/multus.d/multus.kubeconfig" every Multus Pod starts if I understand correctly.

**Comment by Icarus9913** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#safe-rollout-of-time-bound-token

**Comment by Icarus9913** [comment]
https://github.com/spidernet-io/spiderpool/pull/2230

I add the preStop to remove multus CNI configurations after you delete the multus pod or uninstall multus.
