### ISSUE TITLE
multi-cluster feature

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2197]
(1) spec.ips of ippool cr could be synchronized from other clusters, and these information could be used to block new overlayped ips in webhook 
(2) support submariner

**Comment by ty-dc** [comment]
Can it be updated? @Icarus9913

**Comment by Icarus9913** [comment]
same with https://github.com/spidernet-io/spiderpool/issues/1217

**Comment by Icarus9913** [comment]
The submariner is already supported

**Comment by ty-dc** [comment]
https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/submariner-zh_CN.md
