### ISSUE TITLE
coordinator

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2223]
![企业微信截图_e30ac80c-c0ea-4eb3-8918-ac8deefbff45](https://github.com/spidernet-io/spiderpool/assets/45163302/d5d08778-c21a-40b2-a6a7-24d39e672e1b)

* 对于 hijack 等 字段，如果管理员创建时没写，webhook 建议 注入 为空，使得 能够看到 这个配置
* 支持 对 不写 subnet length 时，认定是 32 或者 128 长度 ，可 webhook 帮助下

**Comment by cyclinder** [comment]
fixed by https://github.com/spidernet-io/spiderpool/pull/2314
