### ISSUE TITLE
test division of labour

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#225]
# e2e case for functional test

| case id | category  | title | check point            | priority | status | other |
|---------|-----------|-------|------------------------|----------|--------|-------|
| E00003  | ipam |  two pods in one statefulset  assign / releases ip  | | | | |
| E00004  | ipam |  two pods in one damonset  assign / release ip | | | | |
| E00005  | ipam |  two pods in one job  assign / releases ip | | | | |
| E00006  | ipam |  two pods in one replicaset  assign / release ip | | | | |

**Comment by ty-dc** [comment]
testcases---to do

| case_id |  category   | title                                    | Check point                              | Status | owner |
| :-----: | :---------: | :--------------------------------------- | :--------------------------------------- | :----: | ----- |
| E00001  |  assign ip  | assign ip to a pod for case ipv4, ipv6, dual-stack ip |                                          |  down  |       |
| E00002  |  assign ip  | two pods in one deployment assign / releases ipv4, ipv6 addresses |                                          |        |       |
| E00003  |  assign ip  | two pods in one statefulSet assign / releases ipv4, ipv6 addresses |                                          |        |       |
| E00004  |  assign ip  | two pods in one daemonset assign / releases ipv4, ipv6 addresses |                                          |        |       |
| E00005  |  assign ip  | two pods in one job assign / releases ipv4, ipv6 addresses |                                          |        |       |
| E00006  |  assign ip  | two pods in one  replicaset  assign / releases ipv4, ipv6 addresses |                                          |        |       |
| E00007  |  assign ip  | an invalid IPv4 or IPv6 pool passed in annocation mode cannot be assigned an IP address. |                                          |        |       |
| E00008  |    gc ip    | After the namespace is deleted, the pod IP under the namespace is reclaimed |                                          |        |       |
| E00009  |  assign ip  | create a pod using long yaml，assign / releases ipv4, ipv6 addresses |                                          |        |       |
| E00010  | performance | there are different pods（100、200） in the Deployment creation and the time is less than 3 or 5 minutes after the IP is assigned | Time consuming requires a baseline set of data |        |       |
| E00011  | performance | update deployment to 100 pods, less than 5 minutes after IP assignment | daemonset、sts ==                         |        |       |
| E00012  | performance | delete the deployment copy 100 pods and assign the IP in less than 5 minutes | E00010 and E00011 and E00012  Integrate into one IT |        |       |
| E00013  |    chaos    | IP address allocation, spiderpool pod service failure | Function encapsulation--- piling         |        |       |
| E00014  |    chaos    | IP address allocation, k8s service api-server  failure |                                          |        |       |
| E00015  |    chaos    |                                          |                                          |        |       |
