### ISSUE TITLE
cases E00009 E00013-E00016

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/spiderpool#227]
| case id | tester  | title                                        | check point            | priority | status | other |
|---------|-----------|----------------------|------------------------|----------|--------|-------|
| E00009  | bingzhe | The CNI bin is removed and the GC is verified | | | | |
| E00013  | bingzhe | the IP address allocated is consistent with the address  by the CRD | | | | |
| E00014  | bingzhe | After the namespace is deleted, the pod IP under it is recycled | | | | |
| E00015  | bingzhe | After the IP address is released, it can be used again | | | | |
| E00016  | bingzhe | Create a pod using long yaml | | | | |

**Comment by weizhoublue** [comment]
if done, close it

**Comment by weizhoublue** [comment]
add the PR number

**Comment by ty-dc** [comment]
#263 
#248 
#341 
#323 
#261
