### ISSUE TITLE
stag status of nightly 

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2292]
a PR ci is not expected to update the status of "nightly E2E CI" tag

**Comment by ty-dc** [comment]
Okay, I know

**Comment by ty-dc** [comment]
We only have the following types of badges. "PR ci" will only update the performance badge, so should it not be updated ?
<img width="901" alt="image" src="https://github.com/spidernet-io/spiderpool/assets/101157744/05a14827-dcd7-4186-ae95-c2efd9784f18">

**Comment by ty-dc** [comment]
No need to change.
