### ISSUE TITLE
macprefix for ipvlan

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2385]
macprefix of coordinator is not suitable for ipvlan, only available for sriov and macvlan

so the webhhook of coordinator may give thoughts to reject that case

**Comment by ty-dc** [comment]
This question should be updated, what is the current status? @cyclinder

**Comment by cyclinder** [comment]
I will working on this in next release.

**Comment by cyclinder** [comment]
https://github.com/spidernet-io/spiderpool/pull/2587
