### ISSUE TITLE
[feature] add spidernode CRD which preallocted ips for each node

### ISSUE THREAD

**Issue by yylt** [spidernet-io/spiderpool#2465]
**1 Code requirement**

**2 observe opensource license**

**3 sign-off your commit**

**4 Is your feature request related to a problem? Please describe.**

**5 Describe the solution you'd like**

Now in aws ECS environment could [eni-cni](https://github.com/aws/amazon-vpc-cni-k8s), and design like eni in [ciliumnodes resource](https://github.com/cilium/cilium/blob/aceea7df6e91964b61154e64b634d6ef320e4dc5/pkg/k8s/apis/cilium.io/v2/types.go#L374C45-L374C45) 
maybe spidernet could add another CRD, like spidernode which will preallocte ips for each node, because ip is from vpc, but only support ip not subnat, so spidernode record ip list which is preallocted. 

below is some likely steps:

- daemon(spider agent)
  - Use spidernode as the source for IP allocation
  - Synchronize spidernode and spiderpool resources
  - Can do some extra operations on nodes, such as adding network interfaces, setting IP/MAC etc.

- controller(spider controller)
  -  Create and update spidernode from spiderpool
  - Synchronize spec, status information with daemon decision

**6 Describe alternatives you've considered**

**7 Additional context**

**Comment by Icarus9913** [comment]
@yylt Hi, it looks like a public cloud vpc support right?
At present, in the public cloud with spiderpool usage you could just define every node IPs for different SpiderIPPool resource with `IPPool.Spec.NodeName` or `IPPool.Spec.NodeAffinity` to restrict this SpiderIPPool resource only serves for the Node you specified.

And you could check [alibaba cloud](https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/install/cloud/get-started-alibaba.md) and [aws cloud](https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/install/cloud/get-started-aws-zh_CN.md) blogs.

For the new CRD support, our team will talk or add some public cloud support later. And you could also commit a PR to solve this proposal if you would like.

Thansk.

**Comment by weizhoublue** [comment]
some CNIs record the ip resource in Node object, spiderpool record it in SpiderIPPool, currently, the affinity settings of SpiderIPPool support to bind some IP resource to a specific interface of a specific vm. That is convenient for creating an ipvlan interface from a specific master interface

I think the SpiderIPPool way also meet the same expectation

**Comment by yylt** [comment]
Another reason， as https://spidernet-io.github.io/spiderpool/v0.7/reference/crd-spiderippool description.
The `spec.ips` is iprange format which can not compatible with eni

**Comment by Icarus9913** [comment]
close by #2536
