### ISSUE TITLE
the calico version should be latest by default

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2481]
https://github.com/spidernet-io/spiderpool/blob/main/test/Makefile.defs#L60

compatibility bug could be found in time with latest version

refer to https://github.com/spidernet-io/egressgateway/commit/8c72bd1bc286a9f9ec4d436d168c0fed3ef8d74c#diff-6f9804457d2dee8ff8c16810e42f15317075ed2f12853bb30771441e06c7318b

**Comment by ty-dc** [comment]
fix #2612
