### ISSUE TITLE
support to release latest version of doc

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2482]

**Comment by ty-dc** [comment]
Supports the latest branch and can generate development documents.

The design is as follows:
In the github interface you can pass in the parameter dev and use it to confirm whether your documentation should be set to the latest version. This value defaults to false. When it is false, the generated document will be judged based on whether the document version exists and whether it is a release version.

If this value is true, development documentation will be generated based on the current branch. Its format is v0.8.0 (dev) or v0.7 (dev). By the way, there will only be one development version document at a time, no matter what branch it is based on.

**Comment by ty-dc** [comment]
fix #2546
