### ISSUE TITLE
It is recommended to update sriov-network-device-plugin to v3.6.0

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#2508]
More than a year behind

**Comment by cyclinder** [comment]
The version of the sriov-network-device-plugin is actually determined by the sriov-network-operator. The latest version of the sriov-network-operator is v1.2.0(see https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases).  We need to wait for its new release to update the version of the sriov-network-operator.
