### ISSUE TITLE
add spidernode resource

### ISSUE THREAD

**Issue by yylt** [spidernet-io/spiderpool#2536]
### What would you like to be added?

new resource `spidernode`

### Why is this needed?

spidernode crd is a new resource type that addresses the following issues:

- It provides a local IP list cache, so when requesting or releasing an IP, the address could not directly allocated from the ippool.
- It does the preparation work required before the IP is assigned to a node. This is especially in public cloud scenarios with elastic network interfaces (ENIs), where the IP needs to be bound to the node before it can be used. Additionally, the IP can be classified as primary or secondary, with the primary IP assigned to the host and the secondary IP assigned to containers.

There are some differences between spidernode and spiderippool:

- The addresses in ippool do not have a primary or secondary classification.
- When multiple nodes are using the same ippool, it is not possible to specify a certain set of IPs to be allocated only to specific nodes. This situation often occurs in scenarios where multiple nodes correspond to multiple ippools.

For more information about ENIs, you can refer to the following link: https://github.com/AliyunContainerService/terway/blob/main/docs/design.md#eni%E5%A4%9Aip

### How to implement it (if possible)?

controller add new actions:

1. Allocate addresses from ippool to node.spec resources based on pre-allocation policies.
2. Will do some operations in the ENI scenario, include setting node.status, setting addresses on the host and thus these addresses can be allocated to containers.
3. Mark address availability status and does reclamation.

daemon add new actions:

1. Request and allocate addresses based on their sources, which can be from ippool, node, or ENI.
2. For addresses coming from the ENI source, additional actions are taken to mark the addresses as used.
3. Adjust priority strategies when addresses are sourced from node and ENI.

### Additional context

related:  https://github.com/spidernet-io/spiderpool/issues/2465

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by yylt** [comment]
@weizhoublue  WDYT ?

**Comment by Icarus9913** [comment]
After the conversation, the Node ENI allocation should be handled by the Iaas controller. Spiderpool is a CNI plugin, it serves for the container IP allocation. We don't allocate IP for the Node secondary NIC.
