### ISSUE TITLE
Are there meaningless fields?

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#2543]
### Spiderpool Version

v0.8.0-rc1

### Bug Type

IPAM

### Main CNI

macvlan

### What happened?

In version 0.7.0 or 0.6.0, we've removed the default subnet feature. ？

And when adjusting the default pool, we use spec.default, which controls the default condition of the pool by true or false.

Therefore, ClusterDefaultIPv4IPPool, ClusterDefaultIPv6IPPool, ClusterDefaultIPv4Subnet, and ClusterDefaultIPv6Subnet in the following configmap are actually meaningless?
```
	// configmap
	IpamUnixSocketPath                string   `yaml:"ipamUnixSocketPath"`
	EnableIPv4                        bool     `yaml:"enableIPv4"`
	EnableIPv6                        bool     `yaml:"enableIPv6"`
	EnableStatefulSet                 bool     `yaml:"enableStatefulSet"`
	EnableKubevirtStaticIP            bool     `yaml:"enableKubevirtStaticIP"`
	EnableSpiderSubnet                bool     `yaml:"enableSpiderSubnet"`
	ClusterDefaultIPv4IPPool          []string `yaml:"clusterDefaultIPv4IPPool"`
	ClusterDefaultIPv6IPPool          []string `yaml:"clusterDefaultIPv6IPPool"`
	ClusterDefaultIPv4Subnet          []string `yaml:"clusterDefaultIPv4Subnet"`
	ClusterDefaultIPv6Subnet          []string `yaml:"clusterDefaultIPv6Subnet"`
	ClusterSubnetDefaultFlexibleIPNum int      `yaml:"clusterSubnetDefaultFlexibleIPNumber"`
```

### What did you expect to happen?

All work fine.

### How to reproduce it (as minimally and precisely as possible)

https://github.com/spidernet-io/spiderpool/blob/main/cmd/spiderpool-agent/cmd/config.go

**Comment by Icarus9913** [comment]
Yeah, we already removed the configmap cluster default Subnet/IPPools. So, these fields are useless:

```text
	ClusterDefaultIPv4IPPool          []string `yaml:"clusterDefaultIPv4IPPool"`
	ClusterDefaultIPv6IPPool          []string `yaml:"clusterDefaultIPv6IPPool"`
	ClusterDefaultIPv4Subnet          []string `yaml:"clusterDefaultIPv4Subnet"`
	ClusterDefaultIPv6Subnet          []string `yaml:"clusterDefaultIPv6Subnet"`
```
