### ISSUE TITLE
dynamically modify the route in the pod, for scenarios such as egress and overlay-cooperating

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2642]
### What would you like to be added?

dynamically modify the route in the pod, for scenarios such as egress and overlay-cooperating

### How to implement it (if possible)?

eBPF ?

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by ty-dc** [comment]
same as #2775
