### ISSUE TITLE
run a clean-up job when uninstalling

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2653]
### What would you like to be added?

run a clean-up job when uninstalling , so avoid to call clean-up.sh

job
annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed

### How to implement it (if possible)?

d

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Icarus9913** [comment]
next version

**Comment by Icarus9913** [comment]
```text
annotations:
  "helm.sh/hook":post-delete
  "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
```
