### ISSUE TITLE
clean sriov pod

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2822]
### Spiderpool Version

v0.8.0

### Bug Type

Other

### Main CNI

no

### What happened?

after uninstalling spiderpool , still some sriov pod is running

kube-system   sriov-device-plugin-dwlj9                  1/1     Running            0                 24h
kube-system   sriov-device-plugin-whdgf                  1/1     Running            0                 24h
kube-system   sriov-network-config-daemon-mwprv          3/3     Running            15 (24h ago)      30h
kube-system   sriov-network-config-daemon-tcv7w          3/3     Running            15 (24h ago)      30h

### What did you expect to happen?

unisntall them

### How to reproduce it (as minimally and precisely as possible)

simple

**Comment by cyclinder** [comment]
I'll finish it in this release

**Comment by cyclinder** [comment]
https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/430

**Comment by cyclinder** [comment]
https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/564

**Comment by ty-dc** [comment]
fix #https://github.com/spidernet-io/spiderpool/pull/3339
