### ISSUE TITLE
spiderpool-init pod with lots of duplicated error logs

### ISSUE THREAD

**Issue by Icarus9913** [spidernet-io/spiderpool#3111]
### Spiderpool Version

latest

### Bug Type

IPAM

### Main CNI

/

### What happened?

{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}
{"level":"ERROR","ts":"2024-01-19T07:39:12.132Z","caller":"cmd/client.go:192","msg":"failed to get spiderAgent pods: client rate limiter Wait returned an error: context deadline exceeded, retrying..."}

### What did you expect to happen?

/

### How to reproduce it (as minimally and precisely as possible)

One user report that they upgrade their spiderpool from v0.7 to v0.9 and found the spiderpool-init pod has lots of same logs

**Comment by cyclinder** [comment]
the init-pod complains that it can't get the spiderpool-agent pod and keeps trying. You need to check the status of spiderpool-agent in the cluster to see if something else is preventing it from starting.
