### ISSUE TITLE
CI: webhook failure

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#3196]
### Which tests are failing?
it happened many times

https://github.com/spidernet-io/spiderpool/actions/runs/7782401613/job/21218933519?pr=3189

CI: webhook failure

https://github.com/spidernet-io/spiderpool/actions/runs/7805419026/job/21289798371

**Comment by ty-dc** [comment]
https://github.com/spidernet-io/spiderpool/actions/runs/7805419026/job/21289798371

[e2edebugLog 7.txt](https://github.com/spidernet-io/spiderpool/files/14189943/e2edebugLog.7.txt)

**Comment by ty-dc** [comment]
https://github.com/spidernet-io/spiderpool/actions/runs/7857112387/job/21440702593
