### ISSUE TITLE
test cases in June

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/spiderpool#321]
| case id   | title                                                                                      | priority | smoke | status |                     other                     |
|---------|----------------------------------------------------------------------------------------------|----------|-------|--------|-----------------------------------------------|
| E00014  | succeed to create and delete ippool in batches                                               | p2       |       | NA     |                                               |
| E00015  | fail to run a pod when IP resource of an ippool is exhausted                                 | p3       |       | NA     |                                               |
| D00001    | it fails to append an ip that already exists in another ippool to the ippool                      | p2       |       | NA     |       |
| G00002  | the IP of a running pod should not be reclaimed after a same-name pod within a different namespace is deleted   | p1        |       | NA     |       |
| S00002  | an IP who is set in excludeIPs field of ippool, should not be assigned to a pod  | p2       |       | NA     |       |

**Comment by ty-dc** [comment]
#366 
#341 （"E00015", "S00002"）
#323 
#331
