### ISSUE TITLE
multus cni binary and configuration not found in the host

### ISSUE THREAD

**Issue by Icarus9913** [spidernet-io/spiderpool#3289]
### Spiderpool Version

main

### Bug Type

IPAM

### Main CNI

/

### What happened?

The `spiderpool-agent` component runs good, but the `multus` binary and configuration file not found in the host(`/etc/cni/net.d` and `/opt/cni/bin`). 
the helm value `multus.multusCNI.uninstall` was set to be `true`. And the `spiderpool-agent` restarts several times.

I tried to reproduce it in my kind environment, but can't do it. It's very strange. 

### What did you expect to happen?

/

### How to reproduce it (as minimally and precisely as possible)

/

### Additional Context
The spiderpool-agent container has `preStop` hook to clean up the `multus` binary and cni configuration:
 
```text
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - | 
                {{- if .Values.multus.multusCNI.uninstall }}
                rm -f /host/opt/cni/bin/multus || true
                rm -rf /host/etc/cni/net.d/multus.d || true
                rm -f /host/etc/cni/net.d/00-multus.conf || true
                {{- end }}
                {{ .Values.spiderpoolAgent.binName }} shutdown
```

And the initContainer would install the `multus` binary and cni configuration.

**Comment by ty-dc** [comment]
无法确定如何安装的？但在如下的场景中，将会出现你所提到的问题。

1. 你的集群中，并没有自行安装过 multus
2. 安装 spiderpool 时 `--set multus.multusCNI.install=false` 指定了 false

```
~# helm upgrade --install spiderpool spiderpool/spiderpool -n kube-system --version=0.9.2 --set multus.multusCNI.install=false

[root@controller-node-1 bin]# kubectl get po -n kube-system | grep spiderpool
spiderpool-agent-59lkz                                  1/1     Running     0                 3m
spiderpool-agent-srdpg                                  1/1     Running     0                 3m
spiderpool-controller-5769cc7776-ftr6l                  1/1     Running     0                 3m
spiderpool-init                                         1/1     Running     0                 3m

[root@controller-node-1 bin]# pwd && ls multus
/opt/cni/bin
ls: cannot access multus: No such file or directory
[root@controller-node-1 bin]# pwd && ls spiderpool
/opt/cni/bin
spiderpool

[root@controller-node-1 net.d]# pwd && ls
/etc/cni/net.d
10-calico.conflist  calico-kubeconfig
```

**Comment by cyclinder** [comment]
No issue hit so far, I will close it, feel free to reopen this.
