### ISSUE TITLE
Select an anchor to add links rather than manually type it in a markdown editor

### ISSUE THREAD

**Issue by windsonsea** [spidernet-io/spiderpool#3465]
### The Type of Document Issue

Links to anchor

### What's wrong with this document?

Like in PR https://github.com/spidernet-io/spiderpool/pull/3463, it is recommended to type `#` after `.md` and select from the popped list when adding a link to anchors. Avoid manually typing anchors, as it can lead to typos or broken links.

![image](https://github.com/spidernet-io/spiderpool/assets/79828097/31a29a12-11f9-497e-b1cf-80fe286d2e19)

**Comment by windsonsea** [comment]
cc @ty-dc

**Comment by ty-dc** [comment]
fix #3463
