### ISSUE TITLE
link bug: two dead links in the https://github.com/spidernet-io/spiderpool page

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#352]
**Describe the version**
version about:

- spiderpool

**Describe the bug**

-  two dead links in the https://github.com/spidernet-io/spiderpool page

**Hwo To Reproduce**

1. Jump to https://github.com/spidernet-io/spiderpool
2. Click on the link [installation](https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/install.md)
3. Click on the link [ippool usage](https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/allocation.md)

**Expected behavior**

- success to open link

**Screenshots and log**
<img width="908" alt="image" src="https://user-images.githubusercontent.com/101157744/175235934-ae31a0ea-f564-4209-93c9-1b52707aa54d.png">
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/101157744/175236035-9d6f6158-e430-4ebb-b332-fea323a138ba.png">
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/101157744/175236141-404ac20d-70ce-4b84-b28f-d6e834e43c4c.png">

**Additional context**

- None

**Comment by weizhoublue** [comment]
https://github.com/spidernet-io/spiderpool/pull/444
