### ISSUE TITLE
The multus-cni component is more than a year behind the latest version

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#3537]
### Spiderpool Version

latest

### Bug Type

Other

### Main CNI

macvlan

### What happened?

The multus-cni component is more than a year behind the latest version

### What did you expect to happen?

No more than one year if possible

### How to reproduce it (as minimally and precisely as possible)

```
      ## @param multus.multusCNI.image.tag the multus-CNI image tag
      tag: v3.9.3
      # tag: v4.0.2-thick
```

latest : [v4.0.2](https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v4.0.2)

**Comment by cyclinder** [comment]
No plan to use multus 4.0 so far.
