### ISSUE TITLE
The sriov-cni component is more than 1 year behind the latest version

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#3538]
### The Type of Document Issue

Outdated

### What's wrong with this document?

The sriov-cni component is more than 1 year behind the latest version

|                                 | current version  | The latest version    |
|------------------- |---------|------------  |
| sriov-cni                  | v2.7.0   | [v2.8.0 ](https://github.com/k8snetworkplumbingwg/sriov-cni/releases)      |

**Comment by weizhoublue** [comment]
https://github.com/spidernet-io/spiderpool/pull/3733
