### ISSUE TITLE
The sriov-network-device-plugin component is more than 1 year behind the latest version

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#3540]
### The Type of Document Issue

Outdated

### What's wrong with this document?

The sriov-network-device-plugin component is more than 1 year behind the latest version

|                                 | current version  | The latest version    |
|------------------- |---------|------------  |
| sriov-network-device-plugin                 | v3.5.1  | [v3.6.2](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/releases)      |

**Comment by weizhoublue** [comment]
spiderpool-plugins  这个镜像里的插件，维护起来 还是有点发方便，只能运行其环境才知道 里边是什么版本， 并且目前也不知道 哪些落后多少版本了 
我觉得 可以 在 dockerfile 下放一个 版本文件， 按照这个文件中的 版本来构建 。 而 搞一个 每晚 CI ，追踪开源版本 更新和这个文件 ， 从而提交 PR 到  这个文件 。 这个文件有任何的变更，触发 构建镜像的 CI

**Comment by weizhoublue** [comment]
https://github.com/spidernet-io/spiderpool/pull/3733
