### ISSUE TITLE
init-pod: restart agent should wait the multus configMap updated.

### ISSUE THREAD

**Issue by cyclinder** [spidernet-io/spiderpool#3572]
### Spiderpool Version

all

### Bug Type

Other

### Main CNI

all

### What happened?

We hit the issue about pods can't be started due to no default cni config found,  we found the clusterNetwork of configMap is empty, but all logs show works.

### What did you expect to happen?

init-pod: restart agent should wait the multus configMap updated.

### How to reproduce it (as minimally and precisely as possible)

1. install spiderpool

**Comment by weizhoublue** [comment]
why to delay restarting agent ? the problem is the confimap is not updated. Ss there any mechanism in the agent writing the agent ?

**Comment by cyclinder** [comment]
I mean we should be checking the configMap if updated first, and then restart the agent.

**Comment by ty-dc** [comment]
fix #https://github.com/spidernet-io/spiderpool/pull/3732
