### ISSUE TITLE
documentation not clear for 'make setup_dualCni_cilium' command

### ISSUE THREAD

**Issue by haiwu** [spidernet-io/spiderpool#3782]
### Spiderpool Version

latest

### Bug Type

Installation Issue

### Main CNI

cilium

### What happened?

Simply running 'make setup_dualCni_cilium' per webpage doc, and got this error: 
'docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory: unknown.'

### What did you expect to happen?

The doc should be clear to say if ipv6 is disabled, then use this instead: 
E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium

### How to reproduce it (as minimally and precisely as possible)

1. disable ipv6 in linux kernel
2. run 'make setup_dualCni_cilium'

**Comment by ty-dc** [comment]
hi，make setup_dualCni_cilium 将会默认启动 ipv6 设置，可能您遇到是其他问题，比如设置 IPv6 失败？不需要更改文档？
```
- sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
```
