### ISSUE TITLE
Got error 'bpf.vlanBypass: Invalid type. Expected: [null,array], given: integer' when running 'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium'

### ISSUE THREAD

**Issue by haiwu** [spidernet-io/spiderpool#3783]
### Spiderpool Version

latest

### Bug Type

Installation Issue

### Main CNI

cilium

### What happened?

Got error 'bpf.vlanBypass: Invalid type. Expected: [null,array], given: integer' when running 'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium'

### What did you expect to happen?

Should be ok. 

### How to reproduce it (as minimally and precisely as possible)

Got error 'bpf.vlanBypass: Invalid type. Expected: [null,array], given: integer' when running 'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium'

Fixed via --set bpf.vlanBypass={0} instead of --set bpf.vlanBypass=0  in the source code.

**Comment by ty-dc** [comment]
Thank you for your feedback.

Spiderpool has been using the latest version of cilium to deploy tests, but cilium released a new version last week, which changed the fields kubeProxyReplacement and bpf.vlanBypass, resulting in execution failure.

The problem has been fixed, but make setup_dualCni_cilium is based on a stable version, and no new stable version has been released at this stage, so it will still fail.

**Comment by ty-dc** [comment]
https://github.com/spidernet-io/spiderpool/pull/3762/files
