### ISSUE TITLE
'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium' failed due to error with KUBE_PROXY_REPLACEMENT

### ISSUE THREAD

**Issue by haiwu** [spidernet-io/spiderpool#3784]
### Spiderpool Version

latest

### Bug Type

Installation Issue

### Main CNI

cilium

### What happened?

'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium' failed due to error with KUBE_PROXY_REPLACEMENT

### What did you expect to happen?

should be no error. 

### How to reproduce it (as minimally and precisely as possible)

'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium' failed due to error with KUBE_PROXY_REPLACEMENT

Fixed by the following update: 
      KUBE_PROXY_REPLACEMENT=disabled
      if [ "$DISABLE_KUBE_PROXY" = "true" ]; then
        KUBE_PROXY_REPLACEMENT=strict
      fi

Changed to:

      KUBE_PROXY_REPLACEMENT=false
      if [ "$DISABLE_KUBE_PROXY" = "true" ]; then
        KUBE_PROXY_REPLACEMENT=true
      fi

**Comment by ty-dc** [comment]
Thank you for your feedback.

Spiderpool has been using the latest version of cilium to deploy tests, but cilium released a new version last week, which changed the fields kubeProxyReplacement and bpf.vlanBypass, resulting in execution failure.

The problem has been fixed, but make setup_dualCni_cilium is based on a stable version, and no new stable version has been released at this stage, so it will still fail.

**Comment by ty-dc** [comment]
https://github.com/spidernet-io/spiderpool/pull/3762/files
