### ISSUE TITLE
hit new error when running 'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium'

### ISSUE THREAD

**Issue by haiwu** [spidernet-io/spiderpool#3785]
### Spiderpool Version

latest

### Bug Type

Installation Issue

### Main CNI

cilium

### What happened?

hit new error when running 'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium'

template parsing error: template: :1:3: executing "" at <index $.IPAM.Config 1>: error calling index: reflect: slice index out of range
make[3]: *** [Makefile:205: setup_spiderpool] Error 1
make[3]: Leaving directory '/tmp/spiderpool-0.9.4/test'
make[2]: *** [Makefile:37: kind-init] Error 2
make[2]: Leaving directory '/tmp/spiderpool-0.9.4/test'
make[1]: *** [Makefile:16: init_env_with_release] Error 2
make[1]: Leaving directory '/tmp/spiderpool-0.9.4/test'
make: *** [Makefile:317: setup_dualCni_cilium] Error 2

### What did you expect to happen?

should not have error

### How to reproduce it (as minimally and precisely as possible)

Just run 'E2E_IP_FAMILY=ipv4 make setup_dualCni_cilium'.

This seems to be triggered by source code having this line, and it is not working: 

# docker network inspect kind -f {{\(index\ $.IPAM.Config\ 1\).Subnet}}

template parsing error: template: :1:3: executing "" at <index $.IPAM.Config 1>: error calling index: reflect: slice index out of range

Same for this command: 

# docker network inspect kind -f {{\(index\ $.IPAM.Config\ 1\).Gateway}}

template parsing error: template: :1:3: executing "" at <index $.IPAM.Config 1>: error calling index: reflect: slice index out of range

**Comment by cyclinder** [comment]
Hi @haiwu,  `make setup_dualCni_cilium` means that a cilium dual-stack cluster will be setup, but you specify with E2E_IP_FAMILY=ipv4 that this is an ipv4 only cluster, Did you want a ipv4-only cluster?

**Comment by haiwu** [comment]
ah I see. Yes, only want an ipv4-only cluster, with Cilium CNI handling regular pods, and Spiderpool CNI handling kubevirt VM pods.

**Comment by haiwu** [comment]
@cyclinder : I just want to create a test kind cluster which is ipv4-only, with 2 worker nodes, with Cilium as the default CNI, and on top of this kind cluster, to install spiderpool CNI to handle Kubevirt VM pods network test. The purpose is to show case that spiderpool CNI would be able to handle live migration for Kubevirt VMs with Fixed IPs. 

Are there easier steps to achieve the above goal, or it is still easier to get `make setup_dualCni_cilium` to work first? Right now `make setup_dualCni_cilium` is not working for me, so I am wondering if there's alternative path..

**Comment by cyclinder** [comment]
@haiwu You actually want spiderpool to run on ipv4 only, right? Does your environment support ipv6?

**Comment by haiwu** [comment]
@cyclinder : yes, on ipv4 only. no support for ipv6. I took a look at the Makefile for kind e2e for kube-ovn project here: https://github.com/kubeovn/kube-ovn/blob/master/Makefile, and it seems their 'kind-init' is by default ipv4: 
```
.PHONY: kind-init
kind-init: kind-init-ipv4
```

**Comment by cyclinder** [comment]
You can run the following command to setup an ipv4 only cluster for cilium:

```
make e2e_init_cilium -e E2E_IP_FAMILY=ipv4
```

**Comment by haiwu** [comment]
@cyclinder : I just tried this, did 'make build_image', which got no error. But got the following same error as before after running `make e2e_init_cilium -e E2E_IP_FAMILY=ipv4`: 

```
template parsing error: template: :1:3: executing "" at <index $.IPAM.Config 1>: error calling index: reflect: slice index out of range
make[3]: *** [Makefile:234: setup_spiderpool] Error 1
make[3]: Leaving directory '/tmp/spiderpool/test'
make[2]: *** [Makefile:37: kind-init] Error 2
make[2]: Leaving directory '/tmp/spiderpool/test'
make[1]: *** [Makefile:299: e2e_init] Error 2
make[1]: Leaving directory '/tmp/spiderpool'
make: *** [Makefile:336: e2e_init_cilium] Error 2
```

**Comment by haiwu** [comment]
@cyclinder : reading more about this particular patch: https://github.com/spidernet-io/spiderpool/commit/9cf79093a68d7437100b4b7ec0c2779a03900a41, it seems its logic is wrong? 

It pulled out the lines just for ipv6, and put that at the default place, where ipv4 code path would also hit. 

seems we just need to rollback this patch?

**Comment by haiwu** [comment]
after deleting all lines referring to 'subnet1' and 'gateway1' in this file, it now works for `make e2e_init_cilium -e E2E_IP_FAMILY=ipv4`

Also it seems the only way to add more than one worker node for kind cluster is to manually edit file 'test/yamls/global-kind.yaml'?

**Comment by cyclinder** [comment]
> seems we just need to rollback this patch?

Thank you for finding it! It should be improved, Would you be interested in doing a fix?  I'm just asking :) if not, I'll fix it later.

> Also it seems the only way to add more than one worker node for kind cluster is to manually edit file 'test/yamls/global-kind.yaml'?

yes,  we only have one kind worker node by default, If you want more, you just manually edit file `test/yamls/global-kind.yaml`.

**Comment by cyclinder** [comment]
Hey @haiwu, I try to fix it in https://github.com/spidernet-io/spiderpool/pull/3829. Could you help me to test the fix in your local?
