### ISSUE TITLE
CI:  failed to test the connection with  kdoctor

### ISSUE THREAD

**Issue by cyclinder** [spidernet-io/spiderpool#3980]
### Which tests are failing?

https://github.com/spidernet-io/spiderpool/actions/runs/10611257780/job/29410646802?pr=3974

### Job's Link

https://github.com/spidernet-io/spiderpool/actions/runs/10611257780/job/29410646802?pr=3974

**Comment by ty-dc** [comment]
fix https://github.com/spidernet-io/spiderpool/pull/4172
