### ISSUE TITLE
document :  datapath

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#4023]
### The Type of Document Issue

Lacking

### What's wrong with this document?

add a document that describes how data streams go in all scenarios, for instances:

1 two inter-node pods in the the same subnet or across subnet, communicates with clusterIP or pod ip
2  two intra-node pods in the the same subnet or across subnet, communicates with clusterIP or pod ip
3 nodePort for the pod in the entry node or not 
....

**Comment by ty-dc** [comment]
https://github.com/spidernet-io/spiderpool/pull/4218
