### ISSUE TITLE
Could Spiderpool IPAM CNI work if some existing multus is already installed and running on k8s cluster? 

### ISSUE THREAD

**Issue by haiwu** [spidernet-io/spiderpool#4212]
### What help do you need？

Could Spiderpool IPAM CNI work if some existing multus is already installed and running on k8s cluster, and there are a few NAD already created not by spiderpool? Wondering if installing Spiderpool might impact those existing NADs not created via Spiderpool. 

I could see there is an option `--set multus.multusCNI.install=false` for its helm install. So might be it could just work without these concerns.

**Comment by ty-dc** [comment]
Yes, it works, you are correct, configure it with option --set multus.multusCNI.install=false .
