### ISSUE TITLE
workload can not use fixed IP with an namespace fixed Pool

### ISSUE THREAD

**Issue by qiupingdai** [spidernet-io/spiderpool#427]
feature describe：
**example 1：**
namespace 'NS01' bound IP Pool 'P01' （10.6.124.1-100）,users can not deploy  workload with fixed IPs by using IP Pool（10.6.124.1-100）
if workload which deployed with  fixed IP ，it can be only config as following:

NS01-→ P01（10.6.124.1-100）, only deploy workloads without fixed ip 
Workload01 → P02（10.6.124.101-103），deploy workloads with fixed Ip

**example 2:**
Cluster nodes has been seperate into 2 regions with label : region1(node01~node10)  ，and region1 bond Pool ‘p01’(10.6.124.1-100) ;region2(node11-node20),and region2 bond Pool ‘p02’(10.6.124.101-200).

users can not deploy  workload in node01 with fixed IPs by using IP Pool（10.6.124.1-100）

**expect**
workload can  be  deployed with fixed IP, and the fixed IP can be obtained from  IP pool which is bound with namespace or nodes /region

**Comment by weizhoublue** [comment]
it is not the way of  ippool usage 
a new need
