### ISSUE TITLE
CNI loading failure causing spiderIPpool ip exhaustion

### ISSUE THREAD

**Issue by jiayi-1994** [spidernet-io/spiderpool#4295]
### Spiderpool Version

v0.9.7

### Main CNI

macvlan

### bug description

In the case of multiple NICs, if NIC 1 succeeds in assigning an ip from sp1, and NIC 2 fails to assign an ip (maybe sp2 has run out of ip), it will result in a creation failure and cause sp1 to run out of ip as well.

The multus call to cni ADD fails with a DEL rollback, but the SpiderPool is skipped, resulting in an entire SpiderIpool being exhausted.

![lQLPKHRWh_m_4ZHNAY7NA6awQ9UrdVxWqmwHIUbD6K50AA_934_398](https://github.com/user-attachments/assets/0bd93b5b-28a9-414a-8395-3a602641a137)

### What did you expect to happen?

how to fix it  Or use subnet instead ?

**Comment by ty-dc** [comment]
Thanks for your feedback, do you have some spiderpool-controller and agent logs to provide? Also `kubectl describe po` to show the specific error?

**Comment by ty-dc** [comment]
The issue has been reproduced, thank you for reporting it.

**Comment by jiayi-1994** [comment]
Also configure the error annotations, which will also cause the pool to run out :
v1.multus-cni.io/default-network: default/macvlan-ens3
k8s.v1.cni.cncf.io/networks: macvlan-ens3

**Comment by ty-dc** [comment]
> Also configure the error annotations, which will also cause the pool to run out : v1.multus-cni.io/default-network: default/macvlan-ens3 k8s.v1.cni.cncf.io/networks: macvlan-ens3

Did you specify such an annotation?

ipam.spidernet.io/ippools

Can you show what it looks like?

**Comment by jiayi-1994** [comment]
![image](https://github.com/user-attachments/assets/9dca96c5-d525-4936-9bc9-2073ba44cb1f)
![image](https://github.com/user-attachments/assets/896a3bbb-6b36-432b-a651-fc7027aa5c28)
![image](https://github.com/user-attachments/assets/7d77a596-daae-4309-871d-7e9e86e46eea)
