### ISSUE TITLE
CI failure: G00003

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#458]
https://github.com/spidernet-io/spiderpool/runs/7512876703?check_suite_focus=true

**Comment by bzsuni** [comment]
It looks like an occasional problem caused by network instability.
Maybe the principal reason for ci failure:
https://github.com/spidernet-io/spiderpool/runs/7493578100?check_suite_focus=true
Wait until this problem is solved, and then see if there are any errors reported

**Comment by weizhoublue** [comment]
https://github.com/spidernet-io/spiderpool/runs/7512876703?check_suite_focus=true

**Comment by ty-dc** [comment]
#485 
#479
