### ISSUE TITLE
CI : framework api 

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#459]
https://github.com/spidernet-io/spiderpool/runs/7475136584?check_suite_focus=true

when enableIPv4=false in the configmap , field clusterDefaultIPv4IPPool could be ignored and the spiderpool will not create it. 
So the test api GetClusterDefaultIppool could ignore what values the clusterDefaultIPv4IPPool  field is

**Comment by ty-dc** [comment]
The problem is supposed to be caused by a pr: #453 merge, but unfortunately after several attempts I have been unable to reproduce the problem. I will continue to monitor this issue and if the problem reappears I will make changes.
