### ISSUE TITLE
Feature Request: Simply the helm install.

### ISSUE THREAD

**Issue by yankay** [spidernet-io/spiderpool#496]
From the docs : `https://spidernet-io.github.io/spiderpool/usage/install/#by-self-signed-certificates` , the `helm install` needs several steps.

Is there possible to simply the helm install. The user can use only two steps to install the spiderpool.

```
heml repo add spidernet https://spidernet-io.github.io/spiderpool
helm install --name metallb spidernet/spiderpool 
```
Like the https://github.com/helm/charts/tree/master/stable/metallb

**Comment by weizhoublue** [comment]
done
