### ISSUE TITLE
CI failure:  restaring node case  should  also wait for all pod is running

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#527]
Set title to be in the format CI: <test-name>.
https://github.com/spidernet-io/spiderpool/runs/7670581606?check_suite_focus=true
Copy-paste the output the test failure.
<img width="870" alt="image" src="https://user-images.githubusercontent.com/31728060/182856213-118a225c-891e-4e20-a0d0-39d8512b1179.png">

Upload the zip file generated from that test failure.
[dualstack-debuglog_issue_webhook.txt (3).zip](https://github.com/spidernet-io/spiderpool/files/9259998/dualstack-debuglog_issue_webhook.txt.3.zip)

**Comment by weizhoublue** [comment]
duplicated with https://github.com/spidernet-io/spiderpool/issues/482
the spiderpool controller is not ready for running

**Comment by yulng** [comment]
https://github.com/spidernet-io/spiderpool/pull/560

**Comment by weizhoublue** [comment]
这个 怎么会 关了呢 ？ it 是 pending，还有 遗留 未解决

**Comment by yulng** [comment]
case R00006  pending

**Comment by weizhoublue** [comment]
@ty-dc

**Comment by weizhoublue** [comment]
closed, it does not need to restart node
