### ISSUE TITLE
failed to run pod when run case A00002: edit pod annotations about field "route"

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/spiderpool#630]
**Describe the bug**
failed to run pod after edit pod annotations about field "route"

**Hwo To Reproduce**
1. set pod annotations about "route"
2. create pod

**Screenshots and log**
![image](https://user-images.githubusercontent.com/86399306/186134996-a272a49a-f7d0-4b23-92c2-1f8eec39711d.png)

**Comment by ty-dc** [comment]
#629
