### ISSUE TITLE
CI failure: error,long lock(job test)

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#644]
[e2edebugLog 3.txt](https://github.com/spidernet-io/spiderpool/files/9488488/e2edebugLog.3.txt)
https://github.com/spidernet-io/spiderpool/runs/8044060861?check_suite_focus=true

![image](https://user-images.githubusercontent.com/31728060/188414214-77009f5f-d247-4b6e-a4c9-f1e05583f7c6.png)

****

**Comment by ty-dc** [comment]
In process

**Comment by iiiceoo** [comment]
Fixed in #859
