### ISSUE TITLE
CI failure：long lock when run ipv6-only ci job

### ISSUE THREAD

**Issue by Yanansn** [spidernet-io/spiderpool#653]
https://github.com/spidernet-io/spiderpool/runs/8003600050?check_suite_focus=true
![image](https://user-images.githubusercontent.com/46909067/187342109-a3b10823-7371-4601-8d0c-2efecbe07f47.png)

**Comment by bzsuni** [comment]
{"level":"DEBUG","ts":"2022-08-24T21:14:15.678Z","logger":"IP-GarbageCollection","caller":"gcmanager/pod_cache.go:105","msg":"create pod entry '&{PodName:per1219-219031280-99d78bfc-lsl5p Namespace:ns1218-205827656 NodeName:spiderpool0824202647-control-plane EntryUpdateTime:2022-08-24 21:14:15.677541127 +0000 UTC TracingStartTime:2022-08-24 21:14:15.677543228 +0000 UTC TracingGracefulTime:5s TracingStopTime:2022-08-24 21:14:20.677543228 +0000 UTC PodTracingReason:Deleted}'"}
goroutine= 231 : Goroutine took lock 0.11807869 seconds for more than 0.10 seconds
goroutine 231 [running]:
goroutine 231 runtime/debug.Stack()
goroutine 231 	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
goroutine 231 github.com/spidernet-io/spiderpool/pkg/lock.(*internalRWMutex).Unlock(0xc0006f4280)
goroutine 231 	/src/pkg/lock/lock_debug.go:52 +0xb9
goroutine 231 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*PodDatabase).ApplyPodEntry(0xc0006f4280, 0xc0019718c0)
goroutine 231 	/src/pkg/gcmanager/pod_cache.go:106 +0x85f
goroutine 231 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*SpiderGC).onPodDel(0xc000428080, {0x291fb00?, 0xc001936800})
goroutine 231 	/src/pkg/gcmanager/pod_informer.go:122 +0x2c6
goroutine 231 k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
goroutine 231 	/src/vendor/k8s.io/client-go/tools/cache/controller.go:246
goroutine 231 k8s.io/client-go/tools/cache.(*processorListener).run.func1()
goroutine 231 	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:820 +0x155
goroutine 231 k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000088f18)
goroutine 231 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x49
goroutine 231 k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000710840?, {0x2d2e6a0, 0xc00059a960}, 0x1, 0xc000710840)
goroutine 231 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xcf
goroutine 231 k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4aaa25?, 0x3b9aca00, 0x0, 0x80?, 0xc000088f50?)
goroutine 231 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x10e
goroutine 231 k8s.io/apimachinery/pkg/util/wait.Until(...)
goroutine 231 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
goroutine 231 k8s.io/client-go/tools/cache.(*processorListener).run(0xc000428280?)
goroutine 231 	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:812 +0x79
goroutine 231 k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
goroutine 231 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x74
goroutine 231 created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
goroutine 231 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0xe5
