### ISSUE TITLE
CI failure: when run dualstack found long lock

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/spiderpool#663]
https://github.com/spidernet-io/spiderpool/runs/8101037862?check_suite_focus=true

![image](https://user-images.githubusercontent.com/86399306/187585166-265a6026-90cd-42c4-b172-13435145fb6d.png)

{"level":"INFO","ts":"2022-08-30T20:43:11.331Z","logger":"IPAM","caller":"ipam/ipam.go:163","msg":"Filtered IPPool candidates: [{NIC:eth0 CleanGateway:false PoolCandidates:[{IPVersion:4 Pools:[v4pool-430-675056746]} {IPVersion:6 Pools:[v6pool-430-699262130]}]}]","CNICommand":"ADD","ContainerID":"e8717e37199ad63f4602674e45afee093892391366a5008b141b3e901a484dee","IfName":"eth0","NetNamespace":"/var/run/netns/cni-0c2a897b-b7f2-2a54-56e3-f73461d00e19","PodNamespace":"ns430-662418093","PodName":"per430-674938943-5998bd64b5-g7lcp"}
goroutine= 1369 : Goroutine took lock 0.100617881 seconds for more than 0.10 seconds
{"level":"INFO","ts":"2022-08-30T20:43:11.341Z","logger":"IPAM","caller":"ipam/tools.go:77","msg":"Use IPPools from Pod annotation 'ipam.spidernet.io/ippool'","CNICommand":"ADD","ContainerID":"9948796e5c3c6dba7b451a5c1c1fba3c494ea2d6f05415a5aa1675fd43f0975c","IfName":"eth0","NetNamespace":"/var/run/netns/cni-e4c25130-9e7c-759c-2b44-f81997f41679","PodNamespace":"ns430-662418093","PodName":"per430-674938943-5998bd64b5-ftdrv"}
{"level":"INFO","ts":"2022-08-30T20:43:11.342Z","logger":"IPAM","caller":"ipam/ipam.go:153","msg":"Preliminary IPPool candidates: [{NIC:eth0 CleanGateway:false PoolCandidates:[{IPVersion:4 Pools:[v4pool-430-675056746]} {IPVersion:6 Pools:[v6pool-430-699262130]}]}]","CNICommand":"ADD","ContainerID":"9948796e5c3c6dba7b451a5c1c1fba3c494ea2d6f05415a5aa1675fd43f0975c","IfName":"eth0","NetNamespace":"/var/run/netns/cni-e4c25130-9e7c-759c-2b44-f81997f41679","PodNamespace":"ns430-662418093","PodName":"per430-674938943-5998bd64b5-ftdrv"}
{"level":"INFO","ts":"2022-08-30T20:43:11.343Z","logger":"IPAM","caller":"ipam/ipam_config.go:64","msg":"Dual stack network","CNICommand":"ADD","ContainerID":"9948796e5c3c6dba7b451a5c1c1fba3c494ea2d6f05415a5aa1675fd43f0975c","IfName":"eth0","NetNamespace":"/var/run/netns/cni-e4c25130-9e7c-759c-2b44-f81997f41679","PodNamespace":"ns430-662418093","PodName":"per430-674938943-5998bd64b5-ftdrv"}
goroutine 1369 [running]:
goroutine 1369 runtime/debug.Stack()
goroutine 1369 	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
goroutine 1369 github.com/spidernet-io/spiderpool/pkg/lock.(*internalMutex).Unlock(0xc000399840)
goroutine 1369 	/src/pkg/lock/lock_debug.go:81 +0xb9
goroutine 1369 github.com/spidernet-io/spiderpool/pkg/limiter.(*queue).queueUp(0xc00058e400, {0xc000ac1fa0, 0x1, 0x1})
goroutine 1369 	/src/pkg/limiter/queue.go:127 +0x5b3
goroutine 1369 github.com/spidernet-io/spiderpool/pkg/limiter.(*queue).AcquireTicket(0x2a113d8?, {0x2a113d8, 0xc000bc5a40}, {0xc000ac1fa0, 0x1, 0x1})
goroutine 1369 	/src/pkg/limiter/queue.go:75 +0x1eb
goroutine 1369 github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).allocateIPFromPoolCandidates(0xc0003fcc40, {0x2a113d8, 0xc000bc5a40}, 0xc0010b0c80, {0xc000ed1dfc, 0x4}, {0xc001010a80, 0x40}, 0x0, 0xc00110c000)
goroutine 1369 	/src/pkg/ipam/ipam.go:247 +0x156
goroutine 1369 github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).allocateForOneNIC(0xc0003fcc40, {0x2a113d8, 0xc000bc5a40}, 0xc0010a56b0, {0xc001010a80, 0x40}, 0xc00110c000?, 0xc0003d98c0, 0x1?)
goroutine 1369 	/src/pkg/ipam/ipam.go:216 +0x1ef
goroutine 1369 github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).allocateForAllNICs(0xc0003fcc40, {0x2a113d8, 0xc000bc5a40}, {0xc0003db3e0, 0x1, 0xc000bc5a40?}, {0xc001010a80, 0x40}, 0xc000c73fc0?, 0xc00110c000)
goroutine 1369 	/src/pkg/ipam/ipam.go:189 +0x2f1
goroutine 1369 github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).Allocate(0xc0003fcc40, {0x2a113d8, 0xc000bc5a40}, 0xc000d0f3e0)
goroutine 1369 	/src/pkg/ipam/ipam.go:120 +0xc27
goroutine 1369 github.com/spidernet-io/spiderpool/cmd/spiderpool-agent/cmd.(*_unixPostAgentIpamIp).Handle(0xc001102500?, {0xc001102600?, 0xc000d0f3e0?})
goroutine 1369 	/src/cmd/spiderpool-agent/cmd/ipam.go:50 +0xa31
goroutine 1369 github.com/spidernet-io/spiderpool/api/v1/agent/server/restapi/daemonset.(*PostIpamIP).ServeHTTP(0xc000b0de90, {0x2a10148, 0xc000e8d880}, 0xc001102600)
goroutine 1369 	/src/api/v1/agent/server/restapi/daemonset/post_ipam_ip.go:58 +0x2d7
goroutine 1369 github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x2a10148, 0xc000e8d880}, 0xc001102600)
goroutine 1369 	/src/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x96
goroutine 1369 net/http.HandlerFunc.ServeHTTP(0xc000b31d20, {0x2a10148, 0xc000e8d880}, 0x0?)
goroutine 1369 	/usr/local/go/src/net/http/server.go:2109 +0x4e
goroutine 1369 github.com/go-openapi/runtime/middleware.NewRouter.func1({0x2a10148, 0xc000e8d880}, 0xc001088d00)
goroutine 1369 	/src/vendor/github.com/go-openapi/runtime/middleware/router.go:78 +0x316
goroutine 1369 net/http.HandlerFunc.ServeHTTP(0xc000398ce0, {0x2a10148, 0xc000e8d880}, 0x1000573?)
goroutine 1369 	/usr/local/go/src/net/http/server.go:2109 +0x4e
goroutine 1369 github.com/go-openapi/runtime/middleware.SwaggerUI.func1({0x2a10148, 0xc000e8d880}, 0xc001088d00)
goroutine 1369 	/src/vendor/github.com/go-openapi/runtime/middleware/swaggerui.go:90 +0x302
goroutine 1369 net/http.HandlerFunc.ServeHTTP(0xc000479940, {0x2a10148, 0xc000e8d880}, 0x4a9379?)
goroutine 1369 	/usr/local/go/src/net/http/server.go:2109 +0x4e
goroutine 1369 github.com/go-openapi/runtime/middleware.Spec.func1({0x2a10148, 0xc000e8d880}, 0xc001088d00)
goroutine 1369 	/src/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x249
goroutine 1369 net/http.HandlerFunc.ServeHTTP(0xc000479980, {0x2a10148, 0xc000e8d880}, 0x1?)
goroutine 1369 	/usr/local/go/src/net/http/server.go:2109 +0x4e
goroutine 1369 net/http.serverHandler.ServeHTTP({0x2a024d0?}, {0x2a10148, 0xc000e8d880}, 0xc001088d00)
goroutine 1369 	/usr/local/go/src/net/http/server.go:2947 +0x642
goroutine 1369 net/http.(*conn).serve(0xc000c17400, {0x2a113d8, 0xc000681e00})
goroutine 1369 	/usr/local/go/src/net/http/server.go:1991 +0xbe5
goroutine 1369 created by net/http.(*Server).Serve
goroutine 1369 	/usr/local/go/src/net/http/server.go:3102 +0x838

**Comment by ty-dc** [comment]
In process

**Comment by ty-dc** [comment]
2022-09-30: error log

https://github.com/spidernet-io/spiderpool/actions/runs/3154369424/jobs/5131952717
```
[DEBUG] content type: multipart/form-data; boundary=881ac4f39dc6b584f83d36201122ce27fb5b0a08bfef4032c30c57709599
{"level":"DEBUG","ts":"2022-09-29T20:47:50.578Z","logger":"IP-GarbageCollection","caller":"gcmanager/pod_cache.go:105","msg":"create pod entry '{PodName:per4715-336640188-549464c684-spgl7 Namespace:ns4715-336658289 NodeName:spiderpool0929203228-control-plane EntryUpdateTime:2022-09-29 20:47:50.467183869 +0000 UTC TracingStartTime:2022-09-29 20:48:19 +0000 UTC TracingGracefulTime:35s TracingStopTime:2022-09-29 20:48:54 +0000 UTC PodTracingReason:Terminating}'"}
goroutine= 188 : Goroutine took lock 0.11121987 seconds for more than 0.10 seconds
goroutine 188 [running]:
goroutine 188 runtime/debug.Stack()
goroutine 188 	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
goroutine 188 github.com/spidernet-io/spiderpool/pkg/lock.(*internalRWMutex).Unlock(0xc00011a040)
goroutine 188 	/src/pkg/lock/lock_debug.go:52 +0xb9
goroutine 188 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*PodDatabase).ApplyPodEntry(0xc00011a040, 0xc001317b90)
goroutine 188 	/src/pkg/gcmanager/pod_cache.go:106 +0x86b
goroutine 188 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*SpiderGC).onPodUpdate(0xc000424000, {0x29c7420?, 0xc001581000}, {0x29c7420?, 0xc001149c00})
goroutine 188 	/src/pkg/gcmanager/pod_informer.go:91 +0x150
goroutine 188 k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
goroutine 188 	/src/vendor/k8s.io/client-go/tools/cache/controller.go:239
goroutine 188 k8s.io/client-go/tools/cache.(*processorListener).run.func1()
goroutine 188 	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:816 +0x21f
goroutine 188 k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0004faf18)
goroutine 188 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x49
goroutine 188 k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00077c960?, {0x2dfa0a0, 0xc0008e2600}, 0x1, 0xc00077c960)
goroutine 188 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xcf
goroutine 188 k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004faf08?, 0x3b9aca00, 0x0, 0x5?, 0x985f73?)
goroutine 188 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x10e
goroutine 188 k8s.io/apimachinery/pkg/util/wait.Until(...)
goroutine 188 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
goroutine 188 k8s.io/client-go/tools/cache.(*processorListener).run(0xc000424180?)
goroutine 188 	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:812 +0x79
goroutine 188 k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
goroutine 188 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x74
goroutine 188 created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
goroutine 188 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0xe5
{"level":"DEBUG","ts":"2022-09-29T20:47:50.615Z","logger":"IP-GarbageCollection","caller":"gcmanager/pod_cache.go:105","msg":"create pod entry '{PodName:per4715-336640188-549464c684-stq5d Namespace:ns4715-336658289 NodeName:spiderpool0929203228-worker EntryUpdateTime:2022-09-29 20:47:50.615404794 +0000 UTC TracingStartTime:2022-09-29 20:48:20 +0000 UTC TracingGracefulTime:35s TracingStopTime:2022-09-29 20:48:55 +0000 UTC PodTracingReason:Terminating}'"}
```
[e2edebugLog 2.txt](https://github.com/spidernet-io/spiderpool/files/9679988/e2edebugLog.2.txt)
