### ISSUE TITLE
CI failure :failed to get job pod ip address 

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#690]
[e2edebugLog 3.txt](https://github.com/spidernet-io/spiderpool/files/9488488/e2edebugLog.3.txt)
https://github.com/spidernet-io/spiderpool/runs/8044060861?check_suite_focus=true
![image](https://user-images.githubusercontent.com/31728060/187159442-2fda19b5-9fda-4b2f-a56e-f17ec29d91dc.png)

**Comment by ty-dc** [comment]
#692
