### ISSUE TITLE
no nics network card show

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#711]
**Describe the version**
version about:
1. spiderpool 20220912
2. kubernetes Major:"1", Minor:"23", GitVersion:"v1.23.6"

**Describe the bug**
 pod annotation 打好，ippool有一个ip被使用了，但是第二张网卡没有生效
step
1 e2e用例设置 pod annotaion
![企业微信截图_f31d8035-47e3-4325-956f-43755df988d1](https://user-images.githubusercontent.com/31728060/190329136-3b8f5d2e-cc1c-425e-a2b0-e957910dc3d4.png)

2 查看pod 的网卡
![企业微信截图_661d939f-815e-4c99-9223-88174b2416bb](https://user-images.githubusercontent.com/31728060/190329213-42c784af-7f7b-42e1-a710-4a33090175cc.png)
3 查看POD使用的yaml
![企业微信截图_0ae19e7b-6d4a-4cef-8aa2-614f11c1e857](https://user-images.githubusercontent.com/31728060/190329263-6fb59487-78cd-4a67-9e0d-8b45ce686113.png)

4 查看两个ippool有ip已被使用
![企业微信截图_20d39049-9ea8-42a5-ac43-f533ceeff657](https://user-images.githubusercontent.com/31728060/190329382-9666f80d-d7c4-4a66-8244-784c1648b40b.png)
![企业微信截图_41e5e079-b6f0-4f32-8355-5d4f0ca4e13b](https://user-images.githubusercontent.com/31728060/190329393-c06b08fc-ff41-41ff-8746-774e7a7a1333.png)

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by yulng** [comment]
EVN Error
➜  spiderpool2 git:(nicyw) kubectl get sp
Unable to connect to the server: net/http: TLS handshake timeout

**Comment by yulng** [comment]
> PR #712 还没合入，issue 就close 了 ？

这个环境有问题，所以暂时关闭

**Comment by iiiceoo** [comment]
你可能需要在待测试多网卡的 Pod Yaml 上补上 multus 的 annotation 以生效第二张由 Spiderpool 分配 IP 的网卡。
截图中 Pod 内所看到的 net1 网卡其实是 e2e 测试环境中默认由 bridge CNI 生效的一张网卡（可能被你误认为是由 Spiderpool 分配 IP 的第二张网卡了）。
同时，你可能需要调整 Pod 上的选池 annotation，将 "interface: net1" 调整为 "interface: net2"，因为 net1 已经被刚才提到的 bridge CNI 占掉了，按照 multus 默认的网卡命名规则，下一张待生效的网卡会叫 net2。
```yaml
annotations:
  k8s.v1.cni.cncf.io/networks: ${MULTUS_CNI_NAMESPACE}/${MULTUS_ADDITIONAL_CNI_NAME}
```

**Comment by yulng** [comment]
修改点
1 net2
2 annotations:
  k8s.v1.cni.cncf.io/networks: ${MULTUS_CNI_NAMESPACE}/${MULTUS_ADDITIONAL_CNI_NAME}
POD中可以看到两个IP了
