### ISSUE TITLE
CI failure：lint_chart_against_release_image / chart-lint-test error，failed to find version

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#725]
Set title to be in the format CI: 
failed to find version

Copy-paste the output the test failure.
```
Run chart_version=`cat VERSION | tr -d ' ' | tr -d 'v' `
##[debug]/usr/bin/bash -e /home/runner/work/_temp/4c8d9a84-5eb8-41b2-afa8-dd1cc5d83f93.sh
error, failed to find version
Error: Process completed with exit code 1.
```

Copy-paste the link of the CI build where that test failure has happen.
https://github.com/spidernet-io/spiderpool/actions/runs/3063476278/jobs/4945591361

Include any output from logs that you think may be relevant (to ease GitHub searches).
<img width="1375" alt="企业微信截图_4633b4a1-1806-498f-8874-9eb674b05c53" src="https://user-images.githubusercontent.com/101157744/190537589-8d087d93-551e-4cb3-90a1-795087597f76.png">

**Comment by weizhoublue** [comment]
https://github.com/spidernet-io/spiderpool/commit/c49ccf2c9fa306a1ea0930d0df3898f32c09abe2
