### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/spiderpool#826]
**Describe the version**
spiderpool: 0.2.2

**Describe the bug**
http: panic serving @: runtime error: invalid memory address or nil pointer dereference

**Screenshots and log**
2022/10/08 21:16:17 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 1305 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1850 +0x110
panic({0x2699f60, 0x3b52410})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).allocateIPFromPoolCandidates(0xc000140750, {0x2d2c878, 0xc000dbaed0}, 0xc00071ee20, {0xc0009ed3cc, 0x4}, {0xc000f9fa00, 0x40}, 0x0, 0xc000d6a800)
        /src/pkg/ipam/ipam.go:351 +0xdf5
github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).allocateForOneNIC(0xc000140750, {0x2d2c878, 0xc000dbaed0}, 0xc000e28de0, {0xc000f9fa00, 0x40}, 0xc000d6a800?, 0xc00074f080, 0x1?)
        /src/pkg/ipam/ipam.go:301 +0x1ef
github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).allocateForAllNICs(0xc000140750, {0x2d2c878, 0xc000dbaed0}, {0xc0001023d8, 0x1, 0xc000dbaed0?}, {0xc000f9fa00, 0x40}, 0x0?, 0xc000d6a800)
        /src/pkg/ipam/ipam.go:273 +0x2f1
github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).allocateInStandardMode(0xc000140750, {0x2d2c878, 0xc000dbaed0}, 0xc00012e3c0, 0x40?, 0xc0009ed3cc?)
        /src/pkg/ipam/ipam.go:202 +0x297
github.com/spidernet-io/spiderpool/pkg/ipam.(*ipam).Allocate(0xc000140750, {0x2d2c878, 0xc000dbaed0}, 0xc00012e3c0)
        /src/pkg/ipam/ipam.go:128 +0x865
github.com/spidernet-io/spiderpool/cmd/spiderpool-agent/cmd.(*_unixPostAgentIpamIp).Handle(0xc000dfbf00?, {0xc000af2000?, 0xc00012e3c0?})
        /src/cmd/spiderpool-agent/cmd/ipam.go:50 +0xa31
github.com/spidernet-io/spiderpool/api/v1/agent/server/restapi/daemonset.(*PostIpamIP).ServeHTTP(0xc000a36210, {0x2d2b5e8, 0xc0001421c0}, 0xc000af2000)
        /src/api/v1/agent/server/restapi/daemonset/post_ipam_ip.go:58 +0x2d7
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x2d2b5e8, 0xc0001421c0}, 0xc000af2000)
        /src/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x96
net/http.HandlerFunc.ServeHTTP(0xc0009f5de0, {0x2d2b5e8, 0xc0001421c0}, 0x10000000043e4bd?)
        /usr/local/go/src/net/http/server.go:2109 +0x4e
github.com/go-openapi/runtime/middleware.NewRouter.func1({0x2d2b5e8, 0xc0001421c0}, 0xc000b42600)
        /src/vendor/github.com/go-openapi/runtime/middleware/router.go:78 +0x316
net/http.HandlerFunc.ServeHTTP(0xc000481940, {0x2d2b5e8, 0xc0001421c0}, 0x1000573?)
        /usr/local/go/src/net/http/server.go:2109 +0x4e
github.com/go-openapi/runtime/middleware.SwaggerUI.func1({0x2d2b5e8, 0xc0001421c0}, 0xc000b42600)
        /src/vendor/github.com/go-openapi/runtime/middleware/swaggerui.go:90 +0x302
net/http.HandlerFunc.ServeHTTP(0xc0007a6100, {0x2d2b5e8, 0xc0001421c0}, 0x4a9379?)
        /usr/local/go/src/net/http/server.go:2109 +0x4e
github.com/go-openapi/runtime/middleware.Spec.func1({0x2d2b5e8, 0xc0001421c0}, 0xc000b42600)
        /src/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x249
net/http.HandlerFunc.ServeHTTP(0xc0007a6140, {0x2d2b5e8, 0xc0001421c0}, 0x1?)
        /usr/local/go/src/net/http/server.go:2109 +0x4e
net/http.serverHandler.ServeHTTP({0x2d1ccf8?}, {0x2d2b5e8, 0xc0001421c0}, 0xc000b42600)
        /usr/local/go/src/net/http/server.go:2947 +0x642
net/http.(*conn).serve(0xc000b34aa0, {0x2d2c878, 0xc00065d4d0})
        /usr/local/go/src/net/http/server.go:1991 +0xbe5
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3102 +0x838

**Comment by ty-dc** [comment]
Waiting for support

**Comment by weizhoublue** [comment]
@iiiceoo @Icarus9913 any update on this issue ?
