### ISSUE TITLE
When ipv6 is not available, there are still input examples, and you can click OK without deleting 

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#863]
When ipv6 is not available, there are still input examples, and you can click OK without deleting
<img width="795" alt="企业微信截图_43d7deaf-cf45-4f1c-87fe-d5059f223819" src="https://user-images.githubusercontent.com/31728060/195571198-91b9abe5-6257-40d2-a11c-b718ff968ed8.png">
<img width="715" alt="企业微信截图_1f21bd26-e4ec-4d20-bc66-928a54ffb150" src="https://user-images.githubusercontent.com/31728060/195571247-d84f1071-4a70-4310-9292-60f6f3757a73.png">

**Comment by weizhoublue** [comment]
your request is not supported by WEBUI
