### ISSUE TITLE
https://github.com/spidernet-io/spiderpool/actions/workflows/auto-release.yaml this workflow does not exist, but still be used in badge statistics

### ISSUE THREAD

**Issue by liyuerich** [spidernet-io/spiderpool#918]
**Describe the version**
version about:
1. spiderpool main branch

**Describe the bug**
https://github.com/spidernet-io/spiderpool/actions/workflows/auto-release.yaml this actions workflow does not exist, but still be used in gitlab badge statistics

instead of this workflow is used in github https://github.com/spidernet-io/spiderpool/actions/workflows/auto-version-release.yaml

**How To Reproduce**
goto gitlab 第五代产品开发向导 - spiderpool 构建状态-其他状态

**Expected behavior**
should use correct actions workflow, and display works as expectation

**Screenshots and log**
<img width="885" alt="image" src="https://user-images.githubusercontent.com/97269208/197442238-7c95d6c4-dc69-4d34-8492-90d3b9e69ac5.png">

**Comment by ty-dc** [comment]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/101157744/198915097-158f10ff-1cbe-4419-84e5-e09674303fd3.png">
