### ISSUE TITLE
Whether SRIOV can fix IP？from wangzhonghan(pre-sale)

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#943]
**usage issue**
1. doubts about how to use the software

**Comment by yulng** [comment]
> **usage issue**
> 
> 1. doubts about how to use the software

Yes, it can be realized in combination with Spiderpool

**Comment by weizhoublue** [comment]
there is no difference when using differnce CNI
refer to 
https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/ippool-affinity-pod.md
