### ISSUE TITLE
the controller did not restart but webhook is not available

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#975]
**Describe the bug**
 the controller did not restart but webhook is not available, from ipv4-only log

**Screenshots and log**
```
kube-system       spiderpool-agent-2hk89                                       1/1     Running     0          12m     172.18.0.2      spiderpool1028202850-control-plane   <none>           <none>            app.kubernetes.io/component=spiderpool-agent,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/name=spiderpool,controller-revision-hash=b74587f44,pod-template-generation=1
kube-system       spiderpool-agent-vq4wc                                       1/1     Running     0          12m     172.18.0.3      spiderpool1028202850-worker          <none>           <none>            app.kubernetes.io/component=spiderpool-agent,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/name=spiderpool,controller-revision-hash=b74587f44,pod-template-generation=1
kube-system       spiderpool-controller-6794bdd4d8-69mdh                       1/1     Running     0          8m      172.18.0.3      spiderpool1028202850-worker          <none>           <none>            app.kubernetes.io/component=spiderpool-controller,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/name=spiderpool,pod-template-hash=6794bdd4d8
kube-system       spiderpool-controller-6794bdd4d8-r555n                       1/1     Running     0          8m      172.18.0.2      spiderpool1028202850-control-plane   <none>           <none>            app.kubernetes.io/component=spiderpool-controller,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/name=spiderpool,pod-template-hash=6794bdd4d8
```

**Additional context**
```
{"level":"ERROR","ts":"2022-10-28T20:52:38.928Z","logger":"spiderpool","caller":"cmd/command_add.go:122","msg":"[POST /ipam/ip][500] postIpamIpFailure  failed to allocate IP addresses in standard mode: failed to mark IP allocation: Internal error occurred: failed calling webhook \"spiderendpoint.spiderpool.spidernet.io\": failed to call webhook: Post \"https://spiderpool-controller.kube-system.svc:5722/mutate-spiderpool-spidernet-io-v1-spiderendpoint?timeout=10s\": dial tcp 172.31.70.102:5722: connect: connection refused","Action":"Add","ContainerID":"c501ad3094d2d67f976ee5564cf476ac8727af7d715ebdd26e04a3c0f15aa999","PodUID":"","PodName":"pod5222-380647340","PodNamespace":"ns5222-357283381","IfName":"eth0"}
```

**CI link**
https://github.com/spidernet-io/spiderpool/actions/runs/3348304779/jobs/5547278203

**Upload the zip file generated from that test failure.**
[ipv4Only-debuglog.txt (1).zip](https://github.com/spidernet-io/spiderpool/files/9906577/ipv4Only-debuglog.txt.1.zip)

**Comment by iiiceoo** [comment]
This should not be an issue. I checked the Pod `pod5222-380647340` in CI details and found that it was actually created in the case of restarting the spiderpool-controller:

![image](https://user-images.githubusercontent.com/53129907/201289172-9f388694-5cce-4fe0-a2c6-891a5ef5bd40.png)

At the same time, I collected the IPAM logs of this Pod in spiderpool-agent. The first time it tried to allocate an IP address, the controller was restarting, so the request for webhook was rejecte. After a while, webhook works normally and everything returns to normal:

![image](https://user-images.githubusercontent.com/53129907/201289956-92b0588e-1a67-4f89-ac68-e682cd0f6ff2.png)

**Comment by iiiceoo** [comment]
By the way, the reason why your CI failed in the use case of scale Deployments should have nothing to do with this. These failures are more likely caused by the slow change (Code performance problems) of some IPPools. Maybe you should increase the timeout of your `context`.
