### ISSUE TITLE
when subnet is deleting, it maybe allow to give back ip

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#977]
**Copy-paste the output the test failure.**
```
{"level":"WARN","ts":"2022-10-28T20:45:37.753Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:348","msg":"SpiderSubnet 'v4-ss-447-955417155' is terminating, no need to scale its corresponding IPPools!"}
```

**Upload the zip file generated from that test failure.**
[dualstack-debuglog.txt (3).zip](https://github.com/spidernet-io/spiderpool/files/9906616/dualstack-debuglog.txt.3.zip)

**Copy-paste the link of the CI build where that test failure has happen.**
https://github.com/spidernet-io/spiderpool/actions/runs/3351609531/jobs/5553206488

**Comment by Icarus9913** [comment]
The log has already updated
https://github.com/spidernet-io/spiderpool/pull/1013
